### ISSUE TITLE
While emerging dev-ros/rviz: librviz.so: undefined reference to YAML::*

### ISSUE THREAD

**Issue by digitables** [ros/ros-overlay#1021]
Hi. I was emerging `dev-ros/rviz`, and it seems like there's a linker issue with librviz.
There's a bunch of missing YAML references, probably because `yaml-cpp` wasn't linked into `librviz.so`.
I've attached the snippet where the build failed, my `emerge --info`, and the `lddtree` of `librviz.so`. The lddtree shows that yaml-cpp isn't linked.

[lddtree-for-librviz-so.txt](https://github.com/ros/ros-overlay/files/6946525/lddtree-for-librviz-so.txt)
[emerge--info.txt](https://github.com/ros/ros-overlay/files/6946533/emerge--info.txt)
[build-log-yaml-snippet.txt](https://github.com/ros/ros-overlay/files/6946513/build-log-yaml-snippet.txt)

**Comment by allenh1** [comment]
@digitables unfortunately, `dev-ros/rviz` is the Gentoo version, so I can't offer much help for you here. Please consider filing a bug report with Gentoo's bug tracker, and placing a link here.
