### ISSUE TITLE
[off-topic-question] What camera driver is available in ROS Lunar

### ISSUE THREAD

**Issue by archenroot** [ros/ros-overlay#103]
I know this goes better to ROS forum, etc. but maybe you can quickly help me here.

I am trying to get USB Camera (laptop built in)  working, **but usb_cam package is not available anymore in Lunar,** it was available in Indigo only which I don't have installed.

Is there any replacement or the package is in the moment only missing? Or what driver you use for USB cams in Lunar?

**Comment by allenh1** [comment]
> I know this goes better to ROS forum, etc. but maybe you can quickly help me here.

Yes, I'll do it this once, but I think you'll usually find that the ros answers forum is even quicker!

> I am trying to get USB Camera (laptop built in) working, but usb_cam package is not available anymore in Lunar, it was available in Indigo only which I don't have installed.

http://wiki.ros.org/Sensors

There's a decent list of cameras there. I think there's a generic one, but I'm not a CV guy.

**Comment by archenroot** [comment]
@allenh1 - I will go next time to wiki and forum...

**Comment by allenh1** [comment]
@achenroot the usb_camera driver was just released in lunar, so you should be able to install it shortly. The next gentoo sync should catch it. If not, let me so and I'll retrigger it.
