### ISSUE TITLE
emerge dev-python/rosdep

### ISSUE THREAD

**Issue by AuthenticEshkinKot** [ros/ros-overlay#14]
I've tried to install dev-python/rosdep on my Gentoo, but emerge failed with message:
http://pastebin.com/cRt3BryZ

Briefly, portage expects size of 107 KiB, but gets 73,82K

'emerge --sync' and 'layman -S' were executed exactly before 'emerge dev-python/rosdep'

**Comment by Alessandro-Barbieri** [comment]
Try now

**Comment by AuthenticEshkinKot** [comment]
@Alessandro-Barbieri 
Same:
https://pastebin.com/5PuHq1qG

**Comment by allenh1** [comment]
Hm... That's... interesting. I am trying a fresh install on one of my computers rn. What architecture/python version do you have?

**Comment by AuthenticEshkinKot** [comment]
@allenh1 
I've got ~amd64 arch with python2.7 and python3.4

**Comment by allenh1** [comment]
Hm... Ya, that's rather odd. I'm definitely at a loss here... Did you try removing the overlay and adding it again? That's the best I can offer until someone else runs into this...

**Comment by Alessandro-Barbieri** [comment]
Maybe is a mirror's issue? Try changing mirror and removing the package archive from `/usr/portage/distfiles/`

**Comment by allenh1** [comment]
@AuthenticEshkinKot I'm gonna close this... This doesn't seem to be a ros-overlay issue.
