### ISSUE TITLE
travis is stuck

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#141]
Why travis always runs out of time?
How much time takes to regenerate all the manifests?

**Comment by allenh1** [comment]
@Alessandro-Barbieri That's a really good question... It's definitely a substancial amount of time. Maybe it could just test Lunar? Do you think you could adjust the CI to do that?

**Comment by Alessandro-Barbieri** [comment]
Maybe this is the problem https://bugs.gentoo.org/show_bug.cgi?id=511154

**Comment by allenh1** [comment]
@Alessandro-Barbieri I think the most prudent move here would be to stop running travis here, and, instead, have a test case on superflore for building common targets that we could run on each rosdistro sync.

**Comment by allenh1** [comment]
closing this in favor of ros-infrastructure/superflore#81.
