### ISSUE TITLE
Multiple Packages showing wrong filesizes

### ISSUE THREAD

**Issue by DasRoteSkelett** [ros/ros-overlay#193]
Hi!
I am new to ros.
I am trying to install ros on gentoo. I come along quite a number of wrong (?) metadata in the ebuild. 
Usually, it is enough to (re-)create the manifest, but I wonder, *why* the files do not match anymore, since in my understanding, the distro files should be stable?!

Attached a sample of a failed build.

Thanks and Regards,

   Matthias
[build.log](https://github.com/ros/ros-overlay/files/1355578/build.log)

**Comment by allenh1** [comment]
> I am new to ros.

Excellent! Welcome!

> Usually, it is enough to (re-)create the manifest, but I wonder, why the files do not match anymore, since in my understanding, the distro files should be stable?!

This has been a recurring theme for me... I too would expect some stability here, but, sometimes, the archives _do_ change size (and my cached distfile doesn't).

But, that's not a big deal. Thanks for reporting the issue, I'll ping you once I've regenerated those manifests.

**Comment by allenh1** [comment]
@DasRoteSkelett Ok, I've regenerated the manifest for you. Though I'm not sure why rosinstall was being downloaded -- note that you can just `emerge ros-[distro]/desktop_full` for kinetic, indigo and lunar (I need to update the kinetic install guide still).

**Comment by DasRoteSkelett** [comment]
Hi @allenh1 
thanks for the quick feedback. I synced and I am trying to emerge once again!

**Comment by DasRoteSkelett** [comment]
There are still some left.
ros-kinetic/catkin for once. Would you prefere a merge request?!

Regards

**Comment by allenh1** [comment]
@DasRoteSkelett The packages under the distro-specific categories are in transition from a mistake I made previously (they get confused between distros). I've gone ahead and fixed this one, but, in the future, a PR is more than welcome!

**Comment by DasRoteSkelett** [comment]
Hi @allenh1 
I bravely submitted a pull request (my first one, so bear with me). Hope it somewhat complies to quality. It does need to be checked, as it "only" worked for me (gcc 6.4.0).

Thanks
