### ISSUE TITLE
[ros-gentoo] Ebuild failures occuring in global scope

### ISSUE THREAD

**Issue by wyc** [ros/ros-overlay#2]
Please see:

https://bugs.gentoo.org/show_bug.cgi?id=557764

**Comment by allenh1** [comment]
I'm not so sure this is still problematic... How do I verify whether or not things are working on their end? I have everything working completely on my end, including an install of desktop_full. Not sure why things are not working for them...

**Comment by wyc** [comment]
It's problematic because if we don't fix it, then the repo may be pulled from the layman list.

**Comment by allenh1** [comment]
Ok. I'll look into it further, then.

**Comment by allenh1** [comment]
In the file pasted, it complains about the syntax used in sdformat's ebuild. I have updated that ebuild to a later version  with the following commit. 2cde3bbd57d03b38740f8008286e0ac8b498d08b

**Comment by allenh1** [comment]
I have fixed (I think) the metadata.xml file as well. 50029722050935fefd07b633eb0051ba365f3cdf

**Comment by wyc** [comment]
great work. thanks for the responsiveness on this!

**Comment by allenh1** [comment]
Absolutely.

**Comment by allenh1** [comment]
It appears to be working as of now.

https://qa-reports.gentoo.org/output/repos/ros-gentoo.html

I'm closing the issue here, but will reopen if it is not fixed.
