### ISSUE TITLE
dev-python/distribute-0.7.3 fails to install with python_targets_python3_5

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#25]
Build log here https://gist.github.com/Alessandro-Barbieri/1ee6321eb4489d16f58be62d0ba47c03

**Comment by allenh1** [comment]
The log looks like you were building with python 3.4... Did you unmask python 3.5?

**Comment by Alessandro-Barbieri** [comment]
Yes I unmasked it.
With python 3.5 enabled won't build, I had to mask it for this package

**Comment by Alessandro-Barbieri** [comment]
Retried now and won't install with python3.4 (same error), can't test with python3.5 because wstool doesn't have it (required as a dependency).

**Comment by allenh1** [comment]
I just check my wstool ebuilds, and it compiled just fine... I'm using Python 3.5. let me try and emerge distribute.

**Comment by allenh1** [comment]
Yup. Distribute emerges just fine on my system. I'd say you have some Python issues.

**Comment by allenh1** [comment]
Closing this for now.

**Comment by Alessandro-Barbieri** [comment]
wstool does not have python3.5 support

look here

https://github.com/ros/ros-overlay/blob/master/dev-python/wstool/wstool-0.1.10.ebuild#L2
https://github.com/ros/ros-overlay/blob/master/dev-python/wstool/wstool-0.1.13.ebuild#L2
https://github.com/ros/ros-overlay/blob/master/dev-python/wstool/wstool-0.1.6.ebuild#L2

**Comment by allenh1** [comment]
That's all well and good, but I think this is a non-issue for the general case.

**Comment by Alessandro-Barbieri** [comment]
It's an issue because distribute wants wstool with the same pythons as itself. If you marked distribute working with x y and z you need to have wstool working with x y and z too. You have Python3.5 enable but I bet your distribute is built only with 2.7 because it's the only supported by it's dependency wstool.

**Comment by allenh1** [comment]
That's a fair point. I'll fix this in a few.

**Comment by allenh1** [comment]
By the way, @Alessandro-Barbieri there will be a bunch of new ebuilds later for arbitrary packages.

The goal is to make it such that

```
# emerge ros-lunar/desktop_full
```

will work. I've been doing that for the past few days, and it will definitely need some testing.

**Comment by Alessandro-Barbieri** [comment]
I'll test it.
Why don't just nuke wstool and use downstream version? They have 0.1.13 (same as latest here) why the right pythons etc.

**Comment by allenh1** [comment]
On May 25, 2017 1:39 PM, Alessandro Barbieri <notifications@github.com> wrote:

I'll test it.
Why don't just nuke wstool and use downstream version? They have 0.1.13 (same as latest here) why the right pythons etc.

That's a fair point. I think that would be wise.

**Comment by Alessandro-Barbieri** [comment]
Is distribute *really* needed?

**Comment by allenh1** [comment]
I don't think it is needed. Try the new install method! Should work!
