### ISSUE TITLE
Indigo ebuilds broken

### ISSUE THREAD

**Issue by gemarcano** [ros/ros-overlay#259]
Some of the ebuilds seem to be missing a newline character and a " between LICENSE and KEYWORDS. 
```
LICENSE="KEYWORDS="~x86 ~amd64 ~arm ~arm64"
```
A `git grep -l | wc -l` reports 93 ebuilds that are impacted by this problem. This was introduced yesterday (Nov. 5) in commit 517c3ba57dae7d0b573daf552c6f1f03c8a5d874.

**Comment by allenh1** [comment]
hm... Let me just revert that one then.

**Comment by allenh1** [comment]
done:  b0e51fa79256d0c01ddcf246a10e08d62155fad0

**Comment by allenh1** [comment]
@gemarcano thanks for the heads up!
