### ISSUE TITLE
rename categories

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#26]
For coherence with downstream, the categories of  `dev-python/rosinstall_generator` and `dev-python/rosinstall` should be moved to `dev-util`

**Comment by allenh1** [comment]
I don't entirely agree with this. I want to make it clear which package is being installed -- the `dev-util` version is under Gentoo's maintenance. Packages from this repository should be very easily differentiated from those maintained by Gentoo's.

**Comment by Alessandro-Barbieri** [comment]
You can add he maintainer metadata

**Comment by allenh1** [comment]
But why do we need to conform to what the downstream people do?

**Comment by Alessandro-Barbieri** [comment]
Don't know, but I had installation errors and maybe the fault is the outdated rosinstall_generator

**Comment by allenh1** [comment]
Could you be more specific as to what your installation errors were? I was able to install lunar the other day just fine.

**Comment by allenh1** [comment]
Regardless, this issue does not to be open anymore. Closing as we have gone off topic, and I don't want to rename the categories (there will be new categories in a few days, by the way. For the rest of the rosdistro packages).
