### ISSUE TITLE
ros-indigo/razer_hydra-0.2.1.ebuild is broken

### ISSUE THREAD

**Issue by rochus** [ros/ros-overlay#268]
The razer_hydro ebuild is broken due to a missing/erroneous LICENSE statement on line 13. Not a big deal, however this in turn breaks for instance eix-update. 

In case you require a patch, find it here: https://gist.github.com/rochus/51e4816e7e3ef6e9f6d934cbb6fdf527

**Comment by allenh1** [comment]
The reason this one broke is because the license could not be resolved: the license in the `package.xml` is mapped to "Public Domain", and I don't have a mapping within superflore to map that to the correct license.

**Comment by gemarcano** [comment]
`/usr/portage/licenses/public_domain` is a candidate for the correct license. It's contents:
```
Software is in the public domain.
```

**Comment by allenh1** [comment]
Good eye, haha. Not sure why I failed to see that before...

**Comment by allenh1** [comment]
Fixed.
