### ISSUE TITLE
webkit_dependency: No definition of [python-qt-bindings-webkit] for OS [gentoo]

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#28]
rosdep gives me:

webkit_dependency: No definition of [python-qt-bindings-webkit] for OS [gentoo]

same as http://answers.ros.org/question/262190/webkit_dependency-no-definition-of-python-qt5-bindings-webkit-for-os-osx/

**Comment by allenh1** [comment]
Please file a ticket in the rosdep repo.

**Comment by allenh1** [comment]
@Alessandro-Barbieri Closing, as it is going to be resolved upstream.
