### ISSUE TITLE
GCC6 and emerging opencv3.3 fails

### ISSUE THREAD

**Issue by MalcolmMielle** [ros/ros-overlay#280]
I have an error emerging ros-lunar/opencv3.3 while using gcc6. This

```
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/ext/string_conversions.h:41:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/bits/basic_string.h:5417,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/string:52,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/stdexcept:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/array:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/tuple:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/bits/stl_map.h:63,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/map:61,
                 from /var/tmp/portage/ros-lunar/opencv3-3.2.0-r6/work/opencv3-3.2.0_build-python2_7/modules/viz/precomp.hpp:49:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
```

It might be an old opencv error more than a ros one. I compiled the opencv master version from github by hand and it works so it seems that modification to handle gcc6 have already been made in the master branch. As the opencv from the main portage is also broken when trying to compile it with feature_2d, I wouldn't say that it would be entirely wise to go with this version for now. 

But maybe, would adding a FLAG option to not compile the opencv version given by ros be a possible solution ?

**Comment by allenh1** [comment]
@MalcolmMielle Ya, my portage version of OpenCV has been failing for a while... I'm not quite sure what to do about this.

I'll look into this when I have a few.

**Comment by MalcolmMielle** [comment]
I've been reporting bug to opencv but they just don't have enough manpower I guess :/

**Comment by concavegit** [comment]
For a temporary fix (from #204), edit src_configure in the ebuild:
```
src_configure() {
    filter-flags '-march=*' '-mcpu=*' '-mtune=*'
    local mycmakeargs=(
        -DENABLE_PRECOMPILED_HEADERS=OFF
    )
    ros-cmake_src_configure
}
```

At least that is what worked for `ros-kinetic/opencv3`

**Comment by allenh1** [comment]
@MalcolmMielle Ok, I can now update the status of this.

![Works On My Machine!](https://user-images.githubusercontent.com/2013091/34651395-702a27d0-f395-11e7-8b98-dd5f00ed21a8.png)

Let me know if this doesn't work for you, and I'll reopen it.

**Comment by MalcolmMielle** [comment]
I am on my branch using computer from source version of openCV :). I'll let you know if I switch to this at some point and it doesn't work :)
