### ISSUE TITLE
grid_map and lunar

### ISSUE THREAD

**Issue by MalcolmMielle** [ros/ros-overlay#282]
Any reason hat the grid_map package is not included in lunar but is in kinetic ? Is it because of ethz_asl hasn't officially ported the package to lunar ?

**Comment by allenh1** [comment]
> Is it because of ethz_asl hasn't officially ported the package to lunar ?

Yes, that's likely why. We don't automatically port packages forward, usually (unless it's critical). If you need that package in lunar, I'd suggest you ping the maintainter of the package.

**Comment by allenh1** [comment]
Fixed by #285.
