### ISSUE TITLE
manifests

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#30]
Please regenerate the manifests.
I strongly suggest to commit via `repoman`.

**Comment by allenh1** [comment]
Why do I need to regenerate the manifests? I regenerate every time I add them...

**Comment by Alessandro-Barbieri** [comment]
Because some manifests are missing.

**Comment by allenh1** [comment]
Which packages are missing manifests?

**Comment by Alessandro-Barbieri** [comment]
homer*

**Comment by allenh1** [comment]
Ok, so, after investigation... I was unable to retrieve the file from their server. They are running a GitLab instance, which gave me a 401 (authentication failure) when I ask for the file.

@mikaelarguedas FYI

**Comment by Alessandro-Barbieri** [comment]
kinetic still have this issue

**Comment by allenh1** [comment]
This is actually the result of rosdep not knowing how to properly fetch tar files from GitLab. That's one of the things on my to-do list.

**Comment by Alessandro-Barbieri** [comment]
`* Manifest not found for '/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0
.2.ebuild'`

**Comment by allenh1** [comment]
Thanks, I'll fix this soon

**Comment by Alessandro-Barbieri** [comment]
WOAH

trying to regenerate the manifests

```
 * ACCESS DENIED:  open_wr:      /usr/lib64/python3.5/site-packages/screenrun-1.0.2-1.0.2.tar.gz

LICENSE=BSD

KEYWORDS=x86
 * ISE:write_logfile: unable to append logfile: ros-indigo_-_screenrun-1.0.2
 * /var/tmp/notmpfs/portage/sys-apps/sandbox-2.10-r3/work/sandbox-2.10/libsandbox/libsandbox.c:check_syscall():989: failure (Bad file descriptor):
 * ISE:
        abs_path: /usr/lib64/python3.5/site-packages/screenrun-1.0.2-1.0.2.tar.gz

LICENSE=BSD

KEYWORDS=x86
        res_path: /usr/lib64/python3.5/site-packages/screenrun-1.0.2-1.0.2.tar.gz

LICENSE=BSD

KEYWORDS=x86
/usr/lib64/libsandbox.so(+0xd847)[0x7efe10928847]
/usr/lib64/libsandbox.so(+0xd968)[0x7efe10928968]
/usr/lib64/libsandbox.so(+0x4ac4)[0x7efe1091fac4]
/usr/lib64/libsandbox.so(+0x4ea1)[0x7efe1091fea1]
/usr/lib64/libsandbox.so(+0x4fa5)[0x7efe1091ffa5]
/usr/lib64/libsandbox.so(open+0xb5)[0x7efe10926a7c]
/bin/bash(+0x5a1e2)[0x563c90ae51e2]
/bin/bash(+0x5adb8)[0x563c90ae5db8]
/bin/bash(+0x22373)[0x563c90aad373]
/bin/bash(+0x22a37)[0x563c90aada37]
/proc/7097/cmdline: /bin/bash /usr/lib/portage/python3.5/ebuild.sh depend

/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild: line 15:  7097 Aborted                 (core dumped) DESCRIPTION="screenrun is a small tool tha
t pushes commands into a screen window.
      Use \"
HOMEPAGE="https://wiki.ros.org"
SRC_URI="https://github.com/dornhege/screenrun-release/archive/release/indigo/screenrun/1.0.2-0.tar.gz - amd64 arm ~arm64"

RDEPEND=" > ${P}-${PV}.tar.gz"

LICENSE="BSD"

KEYWORDS="x86
/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild: line 16: ros-indigo/roscpp: No such file or directory
/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild: line 17: app-misc/screen: No such file or directory
/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild: line 19: $'\nDEPEND=': command not found
/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild: line 20: dev-python/catkin: No such file or directory                               [2207/6818]
/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild: line 21: ros-indigo/catkin: No such file or directory
/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild: line 53: unexpected EOF while looking for matching `"'
/var/lib/layman/ros-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild: line 59: syntax error: unexpected end of file
 * ERROR: ros-indigo/screenrun-1.0.2::ros-overlay failed (depend phase):
 *   error sourcing ebuild
 *
 * Call stack:
 *   ebuild.sh, line 611:  Called die
 * The specific snippet of code:
 *                      source "$EBUILD" || die "error sourcing ebuild"
 *
 * If you need support, post the output of `emerge --info '=ros-indigo/screenrun-1.0.2::ros-overlay'`,
 * the complete build log and the output of `emerge -pqv '=ros-indigo/screenrun-1.0.2::ros-overlay'`.
 * Working directory: '/usr/lib64/python3.5/site-packages'
 * S: '/var/tmp/portage/ros-indigo/screenrun-1.0.2/work/screenrun-1.0.2'
!!! getFetchMap(): aux_get() error reading ros-indigo/screenrun-1.0.2; aborting.
Unable to generate manifest.
```

**Comment by Alessandro-Barbieri** [comment]
> !!! A file is not listed in the Manifest: '/home/travis/build/ros/ros-overlay/travis-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild'
> 
>  * Manifest not found for '/home/travis/build/ros/ros-overlay/travis-overlay/ros-indigo/screenrun/screenrun-1.0.2.ebuild'
> 
> !!! Digest verification failed:
> 
> !!! /home/travis/build/ros/ros-overlay/travis-overlay/ros-kinetic/cartesian_msgs/cartesian_msgs-0.0.3-r1.ebuild
> 
> !!! Reason: Filesize does not match recorded size
> 
> !!! Got: 1233
> 
> !!! Expected: 1234
> 
>  * Digest verification failed:
> 
>  * /home/travis/build/ros/ros-overlay/travis-overlay/ros-kinetic/cartesian_msgs/cartesian_msgs-0.0.3-r1.ebuild
> 
>  * Reason: Filesize does not match recorded size
> 
>  * Got: 1233
> 
>  * Expected: 1234
> 
> !!! Digest verification failed:
> 
> !!! /home/travis/build/ros/ros-overlay/travis-overlay/ros-kinetic/graph_msgs/graph_msgs-0.1.0.ebuild
> 
> !!! Reason: Filesize does not match recorded size
> 
> !!! Got: 1258
> 
> !!! Expected: 1259
> 
>  * Digest verification failed:
> 
>  * /home/travis/build/ros/ros-overlay/travis-overlay/ros-kinetic/graph_msgs/graph_msgs-0.1.0.ebuild
> 
>  * Reason: Filesize does not match recorded size
> 
>  * Got: 1258
> 
>  * Expected: 1259
