### ISSUE TITLE
ros-kinetic/moveit_core-0.9.11 fails to compile: logging methods are not in scope

### ISSUE THREAD

**Issue by pholthau** [ros/ros-overlay#509]
## Example
```
/var/tmp/portage/ros-kinetic/moveit_core-0.9.11/work/moveit_core-0.9.11/exceptions/src/exceptions.cpp: In constructor ‘moveit::ConstructException::ConstructException(const string&)’:
/var/tmp/portage/ros-kinetic/moveit_core-0.9.11/work/moveit_core-0.9.11/exceptions/src/exceptions.cpp:42:3: error: ‘logError’ was not declared in this scope
   logError("Error during construction of object: %s\nException thrown.", what_arg.c_str());
   ^~~~~~~~
```

build.log attached
[build.log.txt](https://github.com/ros/ros-overlay/files/1766894/build.log.txt)

**Comment by allenh1** [comment]
@pholthau Thanks for the fix! Yes, I'm very familiar with that `sed` command, actually.

https://github.com/ros/ros-overlay/blob/3152891873f0e608d3937c306acc66afe2c8bec4/ros-indigo/tf2/files/0001-Update-call-to-logError-and-logWarn.patch#L18-L19

This came from console bridge's latest release -- Gentoo has pushed the curve on it, and the ROS community has lagged behind a bit. If there's not already a PR upstream for this patch, please consider filing one (as it's quite easy for this to go unnoticed).

**Comment by pholthau** [comment]
All of moveit should be cleaned now. As long as this is not released, would you mind merging the patches? Or how do you proceed in such cases?
