### ISSUE TITLE
catkin_make_isolated failure

### ISSUE THREAD

**Issue by dkallen77** [ros/ros-overlay#51]
Portage 2.3.5 (python 3.5.3-final-0, default/linux/amd64/13.0/desktop/gnome/systemd, gcc-5.4.0, glibc-2.23-r3, 4.9.16-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.9.16-gentoo-x86_64-AMD_A10-6800K_APU_with_Radeon-tm-_HD_Graphics-with-gentoo-2.3
KiB Mem:     8132872 total,   4453948 free
KiB Swap:    7812092 total,   7812092 free
Timestamp of repository gentoo: Fri, 02 Jun 2017 01:30:01 +0000
sh bash 4.3_p48-r1
ld GNU ld (Gentoo 2.26.1 p1.0) 2.26.1
app-shells/bash:          4.3_p48-r1::gentoo
dev-lang/perl:            5.24.1-r1::gentoo
dev-lang/python:          2.7.12::gentoo, 3.4.5::gentoo, 3.5.3::gentoo
dev-util/cmake:           3.7.2::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.3::gentoo
sys-apps/openrc:          0.26.3::gentoo
sys-apps/sandbox:         2.10-r3::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.15-r2::gentoo
sys-devel/binutils:       2.26.1::gentoo
sys-devel/gcc:            5.4.0-r3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1::gentoo
sys-kernel/linux-headers: 4.4::gentoo (virtual/os-headers)
sys-libs/glibc:           2.23-r3::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

ros-overlay
    location: /usr/local/portage
    sync-type: git
    sync-uri: http://github.com/ros/ros-overlay
    masters: gentoo

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/chromium/policies/managed/chrome-gnome-shell.json /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/opt/chrome/policies/managed/chrome-gnome-shell.json /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles installsources merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms sign splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j1"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 base berkdb bluetooth branding bzip2 c++11 cairo cdda cdr cli colord cracklib crypt cups cxx dbus dri dts dvd dvdr eds egl emboss encode evo exif extras fam firefox flac fortran gd gdbm gif glamor gles gnome gnome-keyring gnome-online-accounts gpm gstreamer gtk iconv instrospection introspection ipv6 jack joystick jpeg kms latex lcms ldap libnotify libsecret libxml2 mad mng modules mp3 mp4 mpeg multilib mysql mysqli nautilus ncurses nls notification nptl ogg opengl openmp pam pango pcre pdf png policykit ppds psql pulseaudio qt3support readline sasl scanner sdl seccomp session spell ssl staging startup-notification static-libs svg systemd tcpd themes tiff tracker truetype udev udisks unicode upower usb vala vorbis wayland wayland-compositor wxwidgets x264 xattr xcb xml xv xvid xwayland zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput keyboard mouse" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" PYTHON_SINGLE_TARGET="python3_5" PYTHON_TARGETS="python 2_7 python3_5" RUBY_TARGETS="ruby21 ruby22" USERLAND="GNU" VIDEO_CARDS="amdgpu radeon nvidia" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

BUILD LOG:
make: *** [Makefile:139: all] Error 2
^[[31m^[[1m<==^[[0m Failed to process package '^[[1m^[[34mstd_msgs^[[0m':
  Command '['make', '-j4', '-l4']' returned non-zero exit status 2^[[0m

^[[31mReproduce this error by running:^[[0m
^[[32m^[[1m==> ^[[0m^[[0mcd /var/tmp/portage/ros-lunar/std_msgs-0.5.11/work/build_isolated/std_msgs && make -j4 -l4

Command failed, exiting.
 ^[[31;01m*^[[0m ERROR: ros-lunar/std_msgs-0.5.11::ros-overlay failed (install phase):
 ^[[31;01m*^[[0m   (no error message)
 ^[[31;01m*^[[0m
 ^[[31;01m*^[[0m Call stack:
 ^[[31;01m*^[[0m     ebuild.sh, line 115:  Called src_install
^[[31;01m*^[[0m   environment, line 318:  Called die
 ^[[31;01m*^[[0m The specific snippet of code:
 ^[[31;01m*^[[0m       catkin_make_isolated --install --install-space="${D}/${RS_PREFIX}" || die;
 ^[[31;01m*^[[0m
 ^[[31;01m*^[[0m If you need support, post the output of `emerge --info '=ros-lunar/std_msgs-0.5.11::ros-overlay'`,
 ^[[31;01m*^[[0m the complete build log and the output of `emerge -pqv '=ros-lunar/std_msgs-0.5.11::ros-overlay'`.
 ^[[31;01m*^[[0m The complete build log is located at '/var/tmp/portage/ros-lunar/std_msgs-0.5.11/temp/build.log'.
 ^[[31;01m*^[[0m The ebuild environment file is located at '/var/tmp/portage/ros-lunar/std_msgs-0.5.11/temp/environment'.
 ^[[31;01m*^[[0m Working directory: '/var/tmp/portage/ros-lunar/std_msgs-0.5.11/work
 ^[[31;01m*^[[0m S: '/var/tmp/portage/ros-lunar/std_msgs-0.5.11/work/std_msgs-0.5.1

**Comment by allenh1** [comment]
So you couldn't emerge `ros-lunar/std_msgs`, right? Could you please add the build log?

**Comment by allenh1** [comment]
@dkallen77 `catkin_make_isolated` has been completely removed from the build system now. Could you re-emerge things?

```sh
emerge -C dev-python/catkin ros-lunar/*
```

Should clean it up before you try again (absolutely remove all trace of everything, as it is not even a little bit the same).
