### ISSUE TITLE
ros-lunar/rosbag_storage-1.13.6::ros-overlay fails to apply patch

### ISSUE THREAD

**Issue by prfraanje** [ros/ros-overlay#520]
I'm trying to install ros-lunar on my (new) gentoo linux system using  `emerge --ask ros-lunar/ros_base
` but get stuck at applying a patch for `rosbag_storage`. Maybe something goes wrong with environment, the build.log says: 
/var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/temp/environment: line 4203: cd: rosbag_storage-1.13.6: No such file or directory

I cannot find out what goes wrong, but noticed that `files`, which contains the patch-file,  is a symlink:
`# ls -l /var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/files`
lrwxrwxrwx 1 root root 56 Mar  5 19:41 /var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/files -> /var/db/repos/ros-overlay/ros-lunar/rosbag_storage/files

See below the emerge info and build log:

`# emerge --info '=ros-lunar/rosbag_storage-1.13.6::ros-overlay'`

Portage 2.3.19 (python 3.5.4-final-0, default/linux/amd64/17.0/desktop, gcc-6.4.0, glibc-2.25-r10, 4.9.76-gentoo-r1first_trial x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.9.76-gentoo-r1first_trial-x86_64-Intel-R-_Core-TM-_i7-3520M_CPU_@_2.90GHz-with-gentoo-2.4.1
KiB Mem:     6789504 total,   3388008 free
KiB Swap:    8388604 total,   8388604 free
Timestamp of repository gentoo: Mon, 05 Mar 2018 18:00:01 +0000
Head commit of repository gentoo: 1ae8ae1f1e0cfb78e67e664ec6a655844b5b49b0
Timestamp of repository ros-overlay: Mon, 05 Mar 2018 03:03:07 +0000
Head commit of repository ros-overlay: 61260d24ba4945b1b9edf7967934095f4a0ece4d

sh bash 4.4_p12
ld GNU ld (Gentoo 2.29.1 p3) 2.29.1
app-shells/bash:          4.4_p12::gentoo
dev-lang/perl:            5.24.3::gentoo
dev-lang/python:          2.7.14-r1::gentoo, 3.5.4-r1::gentoo
dev-util/cmake:           3.9.6::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.4.1-r2::gentoo
sys-apps/openrc:          0.34.11::gentoo
sys-apps/sandbox:         2.12::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.11.6-r2::gentoo, 1.15.1-r1::gentoo
sys-devel/binutils:       2.29.1-r1::gentoo
sys-devel/gcc:            6.4.0-r1::gentoo
sys-devel/gcc-config:     1.8-r1::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1::gentoo
sys-kernel/linux-headers: 4.13::gentoo (virtual/os-headers)
sys-libs/glibc:           2.25-r10::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-extra-opts:

ros-overlay
    location: /var/db/repos/ros-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/ros-overlay.git
    masters: gentoo

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="rsync://mirror.leaseweb.com/gentoo/ rsync://ftp.snt.utwente.nl/gentoo"
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 berkdb bluetooth branding bzip2 cairo cdda cdr cli consolekit crypt cscope cups cxx dbus dri dts dvdr emboss encode exif fam flac fortran gdbm gif glamor gpm gtk iconv imagemagick imap ipv6 jpeg latex lcms ldap libnotify lua mad mime mng modules mp3 mp4 mpeg multilib ncurses networkmanager nls nptl ogg opengl openmp oss pam pango pcre pdf png policykit ppds pulseaudio python qt3support qt4 qt5 readline sasl sdl seccomp smp sockets spell ssl startup-notification svg tcpd tiff truetype udev udisks unicode upower usb v4l vim-syntax vorbis wifi wxwidgets x264 xattr xcb xft xml xscreensaver xv xvid zlib zsh-completion" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput synaptics" KERNEL="linux" L10N="en en-US en-GB nl de de-DE" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-0" POSTGRES_TARGETS="postgres9_5" PYTHON_SINGLE_TARGET="python3_5" PYTHON_TARGETS="python2_7 python3_5" RUBY_TARGETS="ruby22 ruby23" USERLAND="GNU" VIDEO_CARDS="intel i915 i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LINGUAS, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

`# cat /var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/temp/build.log`

 * Package:    ros-lunar/rosbag_storage-1.13.6
 * Repository: ros-overlay
 * Maintainer: hunter@openrobotics.org
 * Upstream:   dthomas@osrfoundation.org https://github.com/ros-gbp/ros_comm/issues
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python2_7 python_targets_python3_5 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking rosbag_storage-lunar-release-1.13.6.tar.gz to /var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/work
>>> Source unpacked in /var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/work
>>> Preparing source in /var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/work/rosbag_storage-1.13.6 ...
/var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/temp/environment: line 4203: cd: rosbag_storage-1.13.6: No such file or directory
 * Applying various patches (bugfixes/updates) ...
 *   0001-Use-CONSOLE_BRIDGE-prefix-for-logError.patch ...

 * Failed Patch: 0001-Use-CONSOLE_BRIDGE-prefix-for-logError.patch !
 *  ( /var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/files/0001-Use-CONSOLE_BRIDGE-prefix-for-logError.patch )
 *
 * Include in your bugreport the contents of:
 *
 *   /var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/temp/0001-Use-CONSOLE_BRIDGE-prefix-for-logError.patch.out

 * ERROR: ros-lunar/rosbag_storage-1.13.6::ros-overlay failed (prepare phase):
 *   Failed Patch: 0001-Use-CONSOLE_BRIDGE-prefix-for-logError.patch!
 *
 * Call stack:
 *     ebuild.sh, line  124:  Called src_prepare
 *   environment, line 4204:  Called epatch
 *   environment, line 1636:  Called die
 * The specific snippet of code:
 *               die "Failed Patch: ${patchname}!";
 *
 * If you need support, post the output of `emerge --info '=ros-lunar/rosbag_storage-1.13.6::ros-overlay'`,
 * the complete build log and the output of `emerge -pqv '=ros-lunar/rosbag_storage-1.13.6::ros-overlay'`.
 * The complete build log is located at '/var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/temp/environment'.
 * Working directory: '/var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/work/rosbag_storage-1.13.6'
 * S: '/var/tmp/portage/ros-lunar/rosbag_storage-1.13.6/work/rosbag_storage-1.13.6'

` # emerge -pqv '=ros-lunar/rosbag_storage-1.13.6::ros-overlay'`

[ebuild  N    ] ros-lunar/rosbag_storage-1.13.6  USE="{-test}" PYTHON_TARGETS="python2_7 python3_5"

**Comment by allenh1** [comment]
@prfraanje Thanks for the report! It seems that the patch just needs to be removed. I'll do so, then verify that the patches aren't blocking indigo or kinetic. Please don't hesitate to let me know if you find more!

**Comment by allenh1** [comment]
Better, you can even fix some of them yourself (should you feel so inclined!). For documentation purposes, I've shown the fix for this one below.


```
allenh1@hunter-laptop ~/work/ros-overlay $ rm -rf ros-lunar/rosbag_storage/files/
allenh1@hunter-laptop ~/work/ros-overlay $ superflore-gen-ebuilds --only rosbag_storage --ros-distro lunar --output-repository-path ~/work/ros-overlay/
>>>> Creating new branch gentoo-bot-feaQQZAjAQ...
>>>> D	ros-lunar/rosbag_storage/files/0001-Use-CONSOLE_BRIDGE-prefix-for-logError.patch
>>>> Regenerating package 'rosbag_storage'...
>>>> Successfully generated installer for package 'rosbag_storage'.
>>>> Pulling docker image 'allenh1/ros_gentoo_base:latest'...
>>>> Running docker image...
>>>> Generating manifests...
>>>> Running container with command string 'bash -c 'cd /tmp/ros-overlay/ros-lunar/rosbag_storage && repoman manifest''...
>>>> Docker container exited.
>>>> Adding changes...
>>>> Committing to branch gentoo-bot-feaQQZAjAQ...
>>>> Forking repository if a fork does not exist...
>>>> Pushing changes to fork...
>>>> Filing pull-request...
>>>> Successfully filed a pull request.
>>>>   https://github.com/ros/ros-overlay/pull/521
>>>> Successfully synchronized repositories!
allenh1@hunter-laptop ~/work/ros-overlay $ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
allenh1@hunter-laptop ~/work/ros-overlay $ git remote remove github
```

**Comment by prfraanje** [comment]
Thanks! I've to learn some things like superflore, but will work on this.

**Comment by allenh1** [comment]
No problem at all! You don't _have_ to learn `superflore`, but I'm rather partial to it. You can install it with `emerge dev-python/superflore`.
