### ISSUE TITLE
rosbridge_library missing

### ISSUE THREAD

**Issue by pygospa** [ros/ros-overlay#560]
Hey folks,
for my project I need Rosbridge running, which I cannot install due to missing dependencies. I've tried with both **lunar** and **kinetic** (I would actually really need it with **knietic**), but both have the same error message:

```
emerge: there are no ebuilds to satisfy "ros-kinetic/rosbridge_library".
(dependency required by "ros-kinetic/rosbridge_suite-0.8.6::ros-overlay" [ebuild])
(dependency required by "ros-kinetic/rosbridge_suite" [argument])
```

And when searching this repo, it seems like there is a number of dependencies on this package (rosapi, rosbridge_server, mqtt_bridge), that should fail as well.

**Comment by allenh1** [comment]
It looks like there's a rosdep key that needs to be resolved in order to generate that package.

```
$ superflore-gen-ebuilds --only rosbridge_library --ros-distro kinetic
>>>> Working in temporary directory /tmp/tmp0kvsl9et
>>>> Creating new branch gentoo-bot-uXKdjwsMjH...
>>>> 
>>>> Regenerating package 'rosbridge_library'...
!!!! Failed to resolve required dependencies for package rosbridge_library!
!!!!  unresolved: "python-bson"
```

We'll need to get `python-bson`resolved for Gentoo, then push it to the `ros/rosdistro` repo. Any idea what that rosdep key should be?

**Comment by awesomebytes** [comment]
Working on it:
https://github.com/ros/ros-overlay/pull/574/files

&

https://github.com/ros/rosdistro/pull/17553

**Comment by awesomebytes** [comment]
Both things merged, pending on doing a rosdistro sync.

**Comment by awesomebytes** [comment]
All ready @pygospa :)

**Comment by awesomebytes** [comment]
@allenh1 I've tried to regenerate `rosbridge_library` too and it fails:

```
$ superflore-gen-ebuilds --ros-distro kinetic --only rosbridge_library --output-repository-path /home/user/sam/ros-overlay
>>>> Creating new branch gentoo-bot-XUuscxloxw...
>>>> 
>>>> Regenerating package 'rosbridge_library'...
>>>> failed to parse website for package rosbridge_library
!!!! Failed to resolve required dependencies for package rosbridge_library!
!!!!  unresolved: "python-bson"
```

As you can see here: https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L499

The dependency from `rosbridge_library` is `python-bson` as you can see here https://github.com/RobotWebTools/rosbridge_suite/blob/develop/rosbridge_library/package.xml#L28 which should get resolved to the `dev-python/pymongo` Gentoo dependency.

For some reason is not!

**Comment by awesomebytes** [comment]
Ok, I needed to do rosdep update on the machine that ran superflore, lesson learnt. So, yeah, rosbridge_suite is ready! (after merging https://github.com/ros/ros-overlay/pull/596#event-1600194962 )

**Comment by allenh1** [comment]
Can this be closed?

**Comment by pygospa** [comment]
Tested it with the tutorial, everything seems to work fine. Thank you very much! :+1:
