### ISSUE TITLE
ros-kinetic/image_transport_plugins not building on i686

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#582]
I'm still working on the tree of dependencies... but something in image_transport_plugins pulls `dev-ruby/json` which pulls `dev-util/ragel` which pulls `dev-util/colm`... which doesn't compile on 32bit platforms :(.

It's reported as a bug in Gentoo: https://bugs.gentoo.org/630580

The error:
```
bootstrap1: tree.c:953: colm_tree_downref: Assertion `tree->refs > 0' failed.
```

**Comment by awesomebytes** [comment]
Yeah it's:

`ros-kinetic/compressed_image_transport` --> `ros-kinetic/cv_bridge` --> `ros-kinetic/opencv3`... which pulls lots of things, and some of it gets what I wrote in the previous comment.

I'll try to contact the author about it, maybe he has a couple of minutes to try.

**Comment by allenh1** [comment]
While that patch is definitely what ugly looks like, I don't see much that can be avoided in this case. I'll look at the upstream code, try to figure out what's breaking things (because a more proper fix would make me feel comfortable). After that, I'll add the patch to the overlay and try and send it to the gentoo people.

> the package most probably is generating wrong code right now as the assert confirms, but at least I can keep moving forward

:laughing:

**Comment by awesomebytes** [comment]
Useful links:

* Official colm mailing list thread about the bug (June 2017): http://www.colm.net/pipermail/colm-users/2017-June/000173.html
* Gentoo bug tracker about it: https://bugs.gentoo.org/630580
* Redhat bug tracker about almost it (different line, same assert): https://bugzilla.redhat.com/show_bug.cgi?id=1402582

I sent an email to the list (trying to follow up the already existing thread) about the bug and a way to reproduce it.

I just found out that the previous version of `ragel` (which is who pulls the `colm` dependency) does not need `colm`. I'll give a try to install that `ragel` version instead (making it a local package.use rule I guess).

**Comment by allenh1** [comment]
@awesomebytes we might just make that the only version the ebuild uses -- would you mind making a PR into ros/rosdistro again for me?

**Comment by awesomebytes** [comment]
Can we force a specific version? the dependency would look like `dev-util/ragel-6.10` instead of `dev-util/ragel` then?

**Comment by awesomebytes** [comment]
Actually, ragel is not in rosdistro. I don't know how to enforce this.

**Comment by awesomebytes** [comment]
The discussion with the actual author & maintainer of the package is moving: http://www.colm.net/pipermail/colm-users/2018-April/000189.html

**Comment by awesomebytes** [comment]
I found out opencv3 not building as shown in: https://github.com/ros/ros-overlay/issues/592

And then I also found cv_bridge not building with the same CMake error of not finding `boost_python`. I workarounded it again like in https://github.com/ros/ros-overlay/issues/581:

`~/gentoo/etc/portage/patches/ros-kinetic/cv_bridge-1.12.8/0001-Hack-to-make-it-compile.patch`
```
From 526d54bb7d834e29b8c00a8e2139fe07f2d2ba08 Mon Sep 17 00:00:00 2001
From: Sammy Pfeiffer <sammypfeiffer@gmail.com>
Date: Sat, 28 Apr 2018 16:48:15 +1000
Subject: [PATCH] Hack to make it compile

---
 CMakeLists.txt | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 997bef3..1acd3fd 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -6,7 +6,8 @@ find_package(catkin REQUIRED COMPONENTS rosconsole sensor_msgs)
 if(NOT ANDROID)
   find_package(PythonLibs)
   if(PYTHONLIBS_VERSION_STRING VERSION_LESS 3)
-    find_package(Boost REQUIRED python)
+    # find_package(Boost REQUIRED python)
+    message(STATUS "Hack: Not looking for boost_python as the package fails compiling if so")
   else()
     find_package(Boost REQUIRED python3)
   endif()
-- 
1.9.1
```

**Comment by awesomebytes** [comment]
I've seen there is `boost-1.66.0` now... I could give a try to re-emerge eeeeverything. I don't see any change in the ebuild that makes me think this will be fixed in any way... but if I have time I'll try.

**Comment by awesomebytes** [comment]
This is an old issue.  `dev-util/colm` was fixed after providing the author a machine that could reproduce the problem. The following issues may arise again, but are a different issue anyways.
