### ISSUE TITLE
Support python 3.6

### ISSUE THREAD

**Issue by concavegit** [ros/ros-overlay#642]
I notice that all of the ROS 1 packages support python2.7 and python 3.5. Is it be okay to add python 3.6 to PYTHON_COMPAT?

**Comment by allenh1** [comment]
I don't see why not. You'll need to modify [a line](https://github.com/ros-infrastructure/superflore/blob/master/superflore/generators/ebuild/ebuild.py#L143) in `superflore`, first.

After you have done that, you can regenerate whichever packages you want to add 3.6 support to with `superflore-gen-ebuilds --only [pkg]`. I'll be happy to merge any PR's that you do this way!

Cheers!

**Comment by allenh1** [comment]
OK, so if you `emerge superflore`, you should be able to bump any package you'd like (at this moment in time, `dev-python/superflore` is just linked to the master branch of the git repo).

**Comment by concavegit** [comment]
All right. I will do that later in the day, my laptop is not connected to a charger right now.

**Comment by allenh1** [comment]
> All right. I will do that later in the day, my laptop is not connected to a charger right now.

Sounds good to me. Thanks again!
