### ISSUE TITLE
catkin_make does not generate compile_commands.json

### ISSUE THREAD

**Issue by concavegit** [ros/ros-overlay#644]
Running `catkin_make -DCMAKE_EXPORT_COMPILE_COMMANDS=1` does not generate compile_commands.json in `catkin_ws/build`.

Some things I observed when comparing to the ubuntu version which may help pin down the cause:
- `compile_commands.json` is successfully created when making a vanilla c++ project, tested with a hello_world.cpp and a corresponding CMakeLists.txt.

- Sourcing `/opt/ros/melodic/setup.bash`, sourcing `catkin_ws/devel/setup.bash`, creating a dummy project with `catkin_create_pkg test`, then running `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1` in `catkin_ws/src/test` generates `compile_commands.json`  in that directory in ubuntu, but does not in gentoo. This leads me to believe that an environment variable is set differently, as I was invoking cmake in the environment setup by sourcing the mentioned files. However, comparing the outputs of `env` did not yield anything obvious.

- The ubuntu version also generates `catkin_ws/build/gtest`, which the gentoo version does not, even with `dev-cpp/gtest` present and detected in the output of `catkin_make`

I have tried this with both melodic and the installation by `ros-meta/desktop_full`

**Comment by concavegit** [comment]
Can anyone reproduce this?

**Comment by allenh1** [comment]
@concavegit it is highly recommended that you avoid using the `ros-meta` installation, since it's not maintained here (and usually causes things in the environment to get messed up). I'd recommend you remove all ros-meta packages if you want to use the overlay installation.

I'm not able to check that right now, but I can later today.

Also, you can try it out in the docker container.

```
docker run -ti --rm --privileged allenh1/ros_gentoo_base:latest
```

Be sure to do an `emerge --sync` before proceeding, as the image hasn't been rebuilt in a while (something I should do soon, as well).

**Comment by allenh1** [comment]
@nuclearsandwich do you have any advice here?

**Comment by concavegit** [comment]
Using the container, emerging ros-melodic/catkin, and following the reproduction steps the problem persists,  Also, it turns out that creating a dummy project is not necessary to the compile_commands being generated in ubuntu.

**Comment by allenh1** [comment]
> The ubuntu version also generates catkin_ws/build/gtest, which the gentoo version does not, even with dev-cpp/gtest present and detected in the output of catkin_make

I forgot to address this: this could be cause by not having `test` set in your `USE` flags. Maybe experimenting some there will help! If not, I'll look into this in a bit.

**Comment by concavegit** [comment]
The `test` USE flag is handled internally by portage, so I am not sure how to set it.

**Comment by concavegit** [comment]
Turns out that the compile_commands.json in ubuntu was generated due to gtest. Since gentoo does not create the gtest directory, there is no compile_commands.json. Adding other things such as message files to a project on gentoo successfully generated a compile_commands.json.
