### ISSUE TITLE
qt:4 dependencies in ros-kinetic (and others)

### ISSUE THREAD

**Issue by pholthau** [ros/ros-overlay#678]
qt:4 is not in the main tree anymore. How is the general way of handling this?

These are the relevant packages (without indogo):
```
$ grep -r 'dev-qt/qt.*:4' | cut -d ':' -f 1 | uniq | grep -v ros-indigo
ros-kinetic/rh_p12_rn_gui/rh_p12_rn_gui-0.1.0.ebuild
ros-kinetic/manipulator_h_gui/manipulator_h_gui-0.3.1.ebuild
ros-kinetic/thormang3_demo/thormang3_demo-0.3.0.ebuild
ros-kinetic/octovis/octovis-1.8.1.ebuild
ros-kinetic/op3_gui_demo/op3_gui_demo-0.2.2.ebuild
ros-kinetic/op3_offset_tuner_client/op3_offset_tuner_client-0.2.2.ebuild
ros-kinetic/hector_geotiff/hector_geotiff-0.3.5.ebuild
ros-kinetic/qt_tutorials/qt_tutorials-0.2.10.ebuild
ros-kinetic/stdr_gui/stdr_gui-0.3.2.ebuild
ros-kinetic/libsegwayrmp/libsegwayrmp-0.2.10.ebuild
ros-kinetic/thormang3_offset_tuner_client/thormang3_offset_tuner_client-0.3.0.ebuild
sci-electronics/gazebo/gazebo-2.2.1.ebuild
sci-electronics/gazebo/gazebo-6.1.0-r1.ebuild
sci-electronics/gazebo/gazebo-7.11.0.ebuild
ros-melodic/octovis/octovis-1.9.0-r1.ebuild
ros-lunar/octovis/octovis-1.9.0.ebuild
```

**Comment by allenh1** [comment]
> qt:4 is not in the main tree anymore. 

Hm... That's rather inconvenient, isn't it! I think there are two routes we could go here: 

 1. Patch the Qt4 out of those packages
 2. Add Qt4 ebuilds to _this_ tree

I think a mix of those would be appropriate. For the time being, I think the fix is 2, then slowly do 1.

@tfoote do you have an opinion on this?

**Comment by pholthau** [comment]
I just checked http://gpo.zugaina.org if there are old qt packages in overlays. `qtcore` seems to be in some, but `qtxmlpatterns`, for example, it not anywhere.

**Comment by allenh1** [comment]
Do you know, roughly, when they were removed from the gentoo tree?

**Comment by allenh1** [comment]
I imagine ROS indigo is rather hurt by this.

**Comment by pholthau** [comment]
> I imagine ROS indigo is rather hurt by this.

Indeed. And I cannot imagine replacing qt4 dependencies there - hence I left out indigo packages from the above list.

**Comment by pholthau** [comment]
> Do you know, roughly, when they were removed from the gentoo tree?

Found the commit: 2018-08-07 19:37:32 +0200
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=67bb098696b2cc4c0c4b826cebc53aca9ae624df

**Comment by allenh1** [comment]
@pholthau thanks!

> Found the commit: 2018-08-07 19:37:32 +0200

That's certainly better than roughly! If we add these to the tree, we should be good.

**Comment by TheLurps** [comment]
pushed pr for your second route @allenh1

**Comment by pholthau** [comment]
I guess this can be closed now. Dependencies seem to work
