### ISSUE TITLE
Patching of ros-melodic/cartographer fails

### ISSUE THREAD

**Issue by flabrosse** [ros/ros-overlay#696]
Trying to install cartographer and the patching fails.  This is patch /var/t
mp/portage/ros-melodic/cartographer-1.0.0/files/0002-Explicitly-link-gmock-and-g
test.patch, which is there.

It tries with -p0 ("can't find file to patch at input line 14"), -p1 ("checking file CMakeLists.txt \n Hunk #1 FAILED at 183."), -p2, -p3 and -p4 ( all with "can't find file to patch at input line 14").

I guess the CMakeFile.txt file has changed and the patch does not work any more?

**Comment by allenh1** [comment]
>

**Comment by allenh1** [comment]
@flabrosse my bad! Accidentally closed it on you.

> I guess the CMakeFile.txt file has changed and the patch does not work any more?

This is almost for sure what happened. Would you mind fixing the patch for me? If not, I can fix it in the near future.

**Comment by flabrosse** [comment]
spqr-1.3.1 emerges fine.

ceres-solver needs to be emegred with sparse (and lapack) USE flags.

The patch works.  cartographer_ros now emerged.

**Comment by allenh1** [comment]
> ceres-solver needs to be emegred with sparse (and lapack) USE flags.

Hm... Ok, would you mind adding that `USE` flag to the appropriate `rosdep` in the ros/rosdistro repo?

> The patch works. cartographer_ros now emerged.

Great! Let me know if you get it working. I was having trouble with it when I last tried (kept getting a `std::bad_alloc` exception), but that is probably some weirdness on my system's configuration.

**Comment by flabrosse** [comment]
I have never used git and so have no idea how to add the USE flags in the repo (and at the moment life is too short to learn git).  I'm also not sure where the USE flags need to be added.

I ran the first of the two demos given at the bottom of [https://google-cartographer-ros.readthedocs.io/en/latest/](https://google-cartographer-ros.readthedocs.io/en/latest/) and that worked fine, after emerging cartographer_rviz.

**Comment by allenh1** [comment]
> I have never used git and so have no idea how to add the USE flags in the repo (and at the moment life is too short to learn git). I'm also not sure where the USE flags need to be added.

Alright, I don't mind doing it then. ;) I'll tag you in the PR so you can see the process.

> I ran the first of the two demos given at the bottom of https://google-cartographer-ros.readthedocs.io/en/latest/ and that worked fine, after emerging cartographer_rviz.

Great!

**Comment by allenh1** [comment]
Once ros/rosdistro#19354 is merged, I'll swap your patch in and regenerate the packages.

Thanks!
