### ISSUE TITLE
Not all ros-melodic packages have python 3.6 support 

### ISSUE THREAD

**Issue by CrawlerSpider** [ros/ros-overlay#702]
I was wunderring why not all ros-melodic packages support python 3.6
For instance:
[ebuild   R    ] ros-melodic/position_controllers-0.14.2::ros-overlay  USE="-test" PYTHON_TARGETS="python2_7 python3_6 -python3_5" 0 KiB 
[ebuild   R    ] ros-melodic/diagnostic_aggregator-1.9.3::ros-overlay  USE="-test" PYTHON_TARGETS="python2_7 -python3_5" 0 KiB

from the package.xml of each ROS package there is information about python support and in superflore Quellcode I found only this line:
PYTHON_COMPAT=( python{2_7,3_5,3_6} ) 

which means, that all packages should had have support in python 3.6, but it seems to be not the case.

What is the reason for it?

**Comment by allenh1** [comment]
Fixed
