### ISSUE TITLE
ignition-transport:3 dependency missing

### ISSUE THREAD

**Issue by pholthau** [ros/ros-overlay#708]
In the main tree, there is only version `4.0.0-r1`, see
https://packages.gentoo.org/packages/sci-libs/ignition-math

```bash
emerge: there are no ebuilds to satisfy "net-libs/ignition-transport:3=".
(dependency required by "sci-electronics/gazebo-7.11.0::ros-overlay" [ebuild])
(dependency required by "ros-kinetic/gazebo_dev-2.5.17::ros-overlay" [ebuild])
(dependency required by "ros-kinetic/gazebo_plugins-2.5.17::ros-overlay" [ebuild])
(dependency required by "ros-kinetic/gazebo_ros_pkgs-2.5.17::ros-overlay" [ebuild])
(dependency required by "ros-kinetic/simulators-1.3.2::ros-overlay" [ebuild])
(dependency required by "ros-kinetic/desktop_full-1.3.2::ros-overlay" [ebuild])
(dependency required by "ros-kinetic/desktop_full" [argument])
```

**Comment by awesomebytes** [comment]
I ran into the same issue.

I'm testing if changing the dependency of `sci-electronics/gazebo-7.11.0` to just `net-libs/ignition-transport` (and adding a bunchload of package.use rules that I'm triggered to add) works.

Note that I'm on Gentoo Prefix and I keep finding issues with packages not prepared for prefix, so it may take a while until I know if this approach works.

**Comment by pholthau** [comment]
I tried it with `net-libs/ignition-transport-4.0.0-r1` without success (no prefix). I added the dependencies to my personal overlay but the package still fails with a different (ffmpeg or so related) error message, so I don't know whether this fixes the issue:

https://github.com/pholthau/pholthaus-overlay/tree/master/net-libs

**Comment by awesomebytes** [comment]
I'm stuck with this bug: https://bugs.gentoo.org/672602

So I can't go further and check if what I proposed works.

**Comment by pholthau** [comment]
Thanks for merging, @allenh1!
