### ISSUE TITLE
geometry_msgs not building, error: No module named genpy

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#715]
The error:
```
Traceback (most recent call last):
  File "/tmp/gentoo/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/genmsg_py.py", line 44
, in <module>
    import genpy.generator
ModuleNotFoundError: No module named 'genpy'
Traceback (most recent call last):
  File "/tmp/gentoo/opt/ros/kinetic/share/genlisp/cmake/../../../lib/genlisp/gen_lisp.py", line 39, in <module>
    import genlisp
ModuleNotFoundError: No module named 'genlisp'
```
When emerging `ros-kinetic/ros_base`. It happens cause it's trying to generate messages in Python 2.7 and Python 3.6.

I think we need to warn in the wiki directly [Installation Gentoo](http://wiki.ros.org/kinetic/Installation/Gentoo) about the specific fix that is needed:

```
# Force to build just Python 2.7
ros-indigo/* PYTHON_TARGETS: -* python2_7
ros-indigo/* PYTHON_SINGLE_TARGET: -* python2_7
ros-kinetic/* PYTHON_TARGETS: -* python2_7
ros-kinetic/* PYTHON_SINGLE_TARGET: -* python2_7
ros-lunar/* PYTHON_TARGETS: -* python2_7
ros-lunar/* PYTHON_SINGLE_TARGET: -* python2_7
```

(Also opening this issue so it appears in searches).

**Comment by awesomebytes** [comment]
(Closed but related: https://github.com/ros/ros-overlay/issues/230 )

**Comment by allenh1** [comment]
Great -- thanks! Can this be closed then?

**Comment by awesomebytes** [comment]
Yeah. Well, I haven't updated the Melodic instructions (as I also haven't setup CI for it to know it works). But the main point was for you to see it and agree.
