### ISSUE TITLE
Gazebo 9.4.1 not emerging

### ISSUE THREAD

**Issue by allenh1** [ros/ros-overlay#722]
Well, those few days of Gazebo 9 being available were nice...

```
gazebo/rendering/skyx/include/GPUManager.h:134:28: error: ‘Ogre::MaterialPtr’ {aka ‘class std::shared_ptr<Ogre::Material>’} has no member named ‘isNull’
gazebo/rendering/Camera.cc:1348:14: error: ‘Ogre::TexturePtr’ {aka ‘class std::shared_ptr<Ogre::Texture>’} has no member named ‘getPointer’
gazebo/rendering/Distortion.cc:339:41: error: ‘Ogre::MaterialPtr’ {aka ‘class std::shared_ptr<Ogre::Material>’} has no member named ‘isNull’
gazebo/rendering/DepthCamera.cc:103:30: error: ‘Ogre::TexturePtr’ {aka ‘class std::shared_ptr<Ogre::Texture>’} has no member named ‘getPointer’
gazebo/rendering/DepthCamera.cc:140:32: error: ‘Ogre::TexturePtr’ {aka ‘class std::shared_ptr<Ogre::Texture>’} has no member named ‘getPointer’
```

Seems to be an ogre API change. I'll try to patch this later tonight.

---

Additional info:
 * OGRE version: 1.10.12

**Comment by allenh1** [comment]
Looks like we just need to take the `.getPointer` calls and change them to `.get()`, then take the `isNull` calls and just use the user-defined bool conversion operator for `std::shared_ptr`.

**Comment by allenh1** [comment]
```cpp
#if OGRE_VERSION_MAJOR == 1 && OGRE_VERSION_MINOR > 9
#define IS_NULL(x) \
  (!(x))
#else
#define IS_NULL(x) \
  ((x).isNull())
#endif

#if OGRE_VERSION_MAJOR == 1 && OGRE_VERSION_MINOR > 9
#define SET_NULL(x) \
  ((x) = nullptr)
#else
#define SET_NULL(x) \
  ((x).setNull())
#endif
```

These are some useful macros for others -- my full patches will be up soon, I hope. Note: this was not a trivial change.

**Comment by allenh1** [comment]
@tfoote Should I upstream these patches once I have things in a working state?

**Comment by tfoote** [comment]
Are you bumping up to ogre 2? I believe there's already patches toward that support already @iche033 can you point to the best place to contribute any changes for ogre version support?

**Comment by allenh1** [comment]
> Are you bumping up to ogre 2?

No, I'm bumping to 1.10.

Btw, very impressed by how quickly gazebo 9.4.1 starts. Really nice improvements there!

**Comment by allenh1** [comment]
Ok, FINALLY done patching. It was a really, really, not fun time.

https://gist.github.com/allenh1/43883e92e92c1c83a532e4bd6952b2fb#file-gazebo-9-4-1-ogre-1-10-support-patch

**Comment by allenh1** [comment]
Also note: this does not resolve deprecation warnings.

**Comment by iche033** [comment]
we actually don't have any plans on making gazebo work with ogre 2.x. The work I'm doing is for the ignition projects. 

On the other hand, It would be nice for this patch to make it back into gazebo

**Comment by allenh1** [comment]
> On the other hand, It would be nice for this patch to make it back into gazebo

Absolutely! I know gazebo is mercurial so we can't just `git -am` these, but I'd be more than happy to get these upstreamed however you'd like for me to. Let me know!

**Comment by iche033** [comment]
Just clone the repo, branch out of `gazebo9`, and apply your patch using good old `patch` command.

One thing to note is that almost all the changes in the patch could be applied to the `gazebo9` release branch but the `depthTexture` variable type change in DepthCamera.hh may break ABI. I believe you should be able to keep the `depthTexture` untouched in the .hh file but in the .cpp file where the `depthTexture` is [created](https://gist.github.com/allenh1/43883e92e92c1c83a532e4bd6952b2fb#file-gazebo-9-4-1-ogre-1-10-support-patch-L134), just add a `.get()` in the end to get the raw pointer. Create the PR and that'll trigger the jenkins builds including ABI compatibility check

thanks!

**Comment by allenh1** [comment]
Sure thing! I'll get on that at some point this weekend.

**Comment by awesomebytes** [comment]
@allenh1 @pholthau You closed this, is it supposed to emerge? Cause for me it blocks on `sci-libs/ignition-math-6.0.0` with:

```
>>> Configuring source in /home/user/gentoo/var/tmp/portage/sci-libs/ignition-math-6.0.0/work/ignition-math6_6.0.0~pre4 ...
/home/user/gentoo/var/tmp/portage/sci-libs/ignition-math-6.0.0/temp/environment: line 2736: /home/user/gentoo/var/tmp/portage/sci-libs/ignition-math-6.0.0/work/ignition-math6_6.0.0~pre4/cmake/HostCFlags.cmake: No such file or directory
sed: can't read cmake/DefaultCFlags.cmake: No such file or directory
 * ERROR: sci-libs/ignition-math-6.0.0::ros-overlay failed (configure phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 124:  Called src_configure
 *   environment, line 2737:  Called die
 * The specific snippet of code:
 *       sed -i -e "s/LINK_FLAGS_RELWITHDEBINFO \" \"/LINK_FLAGS_RELWITHDEBINFO \" ${LDFLAGS} \"/" cmake/DefaultCFlags.cmake || die;
```
Which effectively is trying to patch a file that does not exist. I tried removing that custom bit of the ebuild (thinking it maybe is not necessary anymore), but no luck:


```
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "Findignition-cmake2.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-cmake2", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-cmake2"
  (requested version 2.0.0) with any of the following names:

    ignition-cmake2Config.cmake
    ignition-cmake2-config.cmake

  Add the installation prefix of "ignition-cmake2" to CMAKE_PREFIX_PATH or
  set "ignition-cmake2_DIR" to a directory containing one of the above files.
  If "ignition-cmake2" provides a separate development package or SDK, be
  sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/user/gentoo/var/tmp/portage/sci-libs/ignition-math-6.0.0/work/ignition-math-6.0.0_build/CMakeFiles/CMakeOutput.log".
 * ERROR: sci-libs/ignition-math-6.0.0::ros-overlay failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_configure
 *   environment, line 2735:  Called cmake-utils_src_configure
 *   environment, line  816:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";

```

**Comment by pholthau** [comment]
I can't speak of gazebo 9, because I only use 7 (which I think is a hard dependency of kinetic). But gazebo 7 should build now? The dependency should be in the overlay now as the PR had been merged but I see it disappeared again. Apparently, it has been deleted in https://github.com/ros/ros-overlay/commit/28b4e3e4be86ec508df6d4c354752b2a267e4d2c @allenh1
