### ISSUE TITLE
rviz_plugin_tutorials-0.10.3 fails to compile (more Ogre stuff)

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#724]
While emerging `ros-kinetic/desktop` (after successfully emerging rviz with the stuff in https://github.com/ros/ros-overlay/issues/723):

```
c/plant_flag_tool.cpp: In member function 'virtual void rviz_plugin_tutorials::PlantFlagTool::onInitialize()':
/home/user/gentoo/var/tmp/portage/ros-kinetic/rviz_plugin_tutorials-0.10.3/work/rviz_plugin_tutorials-0.10.3/src/plant_flag_tool.cpp:90:52: error: 'Ogre::MeshPtr' {aka 'class std::shared_ptr<Ogre::Mesh>'} has no member named 'isNull'
   if( rviz::loadMeshFromResource( flag_resource_ ).isNull() )
```

So more of the same.

**Comment by awesomebytes** [comment]
Patch for it: https://gist.github.com/awesomebytes/b1cc1490045a568b68dcd618629de405

**Comment by allenh1** [comment]
@awesomebytes This patch works for people with OGRE > 1.9, but would break the existing behavior for those using <= 1.9.

```cpp
#if OGRE_VERSION_MAJOR == 1 && OGRE_VERSION_MINOR > 9
#define IS_NULL(x) \
  (!(x))
#else
#define IS_NULL(x) \
  ((x).isNull())
#endif

#if OGRE_VERSION_MAJOR == 1 && OGRE_VERSION_MINOR > 9
#define SET_NULL(x) \
  ((x) = nullptr)
#else
#define SET_NULL(x) \
  ((x).setNull())
#endif
```

This is what I've been applying to Gazebo (still not done btw), and this seems to work pretty well whilst preserving existing code.

**Comment by awesomebytes** [comment]
Made a patch with your style preserving compilation in both versions: 

https://gist.github.com/awesomebytes/b18a18caa62b66c773580baf11c08d10

**Comment by awesomebytes** [comment]
Merged, closing, thank you!
