### ISSUE TITLE
qt_gui_cpp must depend on dev-qt/qtwidgets

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#725]
Depending on the order how `ros-kinetic/desktop` emerges packages I found myself trying to emerge `ros-kinetic/qt_gui_cpp` failing cause of:

```
CMake Error at src/qt_gui_cpp/CMakeLists.txt:3 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/user/gentoo/var/tmp/portage/ros-kinetic/qt_gui_cpp-0.3.11/work/qt_gui_cpp-0.3.11_build/CMakeFiles/CMakeOutput.log".
 * ERROR: ros-kinetic/qt_gui_cpp-0.3.11::ros-overlay failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_configure
 *   environment, line 4056:  Called ros-cmake_src_configure
 *   environment, line 3953:  Called cmake-utils_src_configure
 *   environment, line 1050:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
```

Which was solved doing: 
```bash
emerge dev-qt/qtwidgets
```

And trying again.

This happens cause `qt_gui_cpp` has a dependency on `qtbase5-dev` which for Ubuntu & friends pulls qtwidgets. But not for Gentoo.

My proposal is to add to rosdistro also `dev-qt/qtwidgets` on the key `qtbase5-dev`:

https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L4413-L4418

Let me know what you think. If so, I'll do a PR.

**Comment by awesomebytes** [comment]
And then I ran again into: https://github.com/ros/ros-overlay/issues/592

Hmmm that seems like a problem from `opencv3` not depending on `libqt5-concurrent`.

And `qttest` is part of `qtbase5-dev` in Ubuntu too.

# Proposed solution
So I'd propose to add to the key `qtbase5-dev` in rosdistro `dev-qt/widgets` and `dev-qt/qttest`.

And then propose for the `package.xml` of `opencv3` to add `libqt5-concurrent` as a dependency.

Thoughts @allenh1 ?

**Comment by allenh1** [comment]
Sounds good to me

**Comment by awesomebytes** [comment]
Created a PR with it: https://github.com/ros/rosdistro/pull/19728

**Comment by awesomebytes** [comment]
The PR has been merged. But I gave another check to the opencv3 issue. The thing is. I can't really ask the opencv3 package to depend on any Qt thing as Qt support is optional.  This is again just happening cause Gentoo by default on Qt provides nothing so you need to add all those USE flags or extra qt packages explicitly. @allenh1 Can we patch for ourselves-only the ebuild to add that dependency? I don't know if superflore will manage that correctly (as I don't know how it works).

**Comment by allenh1** [comment]
> Can we patch for ourselves-only the ebuild to add that dependency? I don't know if superflore will manage that correctly (as I don't know how it works).

It will do it when I regenerate the ebuild.

```
superflore-gen-ebuilds --only qt_gui_cpp --ros-distro kinetic
```
