### ISSUE TITLE
rqt python stuff needs dev-python/PyQt5[gui,widgets]

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#729]
Trying to use `rqt` I came up with this error:
```
Traceback (most recent call last):
  File "/tmp/gentoo/opt/ros/kinetic/bin/rqt", line 13, in <module>
    sys.exit(main.main())
  File "/tmp/gentoo/opt/ros/kinetic/lib/python2.7/site-packages/rqt_gui/main.py", line 59, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider, plugin_manager_settings_prefix=str(hash(os.environ['ROS_PACKAGE_PATH'])))
  File "/tmp/gentoo/opt/ros/kinetic/lib/python2.7/site-packages/qt_gui/main.py", line 338, in main
    from python_qt_binding import QT_BINDING
  File "/tmp/gentoo/opt/ros/kinetic/lib/python2.7/site-packages/python_qt_binding/__init__.py", line 55, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/tmp/gentoo/opt/ros/kinetic/lib/python2.7/site-packages/python_qt_binding/binding_helper.py", line 282, in <module>
    getattr(sys, 'SELECT_QT_BINDING_ORDER', None),
  File "/tmp/gentoo/opt/ros/kinetic/lib/python2.7/site-packages/python_qt_binding/binding_helper.py", line 128, in _select_qt_binding
    raise ImportError("Could not find Qt binding (looked for: %s):\n%s" % (', '.join(["'%s'" % b for b in binding_order]), '\n'.join(error_msgs)))
ImportError: Could not find Qt binding (looked for: 'pyqt', 'pyside'):
```

This seems to be cause the (python) rosdistro key `python-qt5-bindings` points in gentoo to `dev-qt/PyQt5` which is not sufficient as rqt-python tools need the additional [gui, widgets] USE flag (It's funny that the in Gentoo PyQt5 would seem to be sufficient for someone... given it provides 0 functionality without the extra USE flags).

I also needed to do
```bash
echo ">=dev-python/PyQt5-5.10.1-r1 gui widgets" >> /tmp/gentoo/etc/portage/package.use
emerge dev-python/PyQt5[gui,widgets]
```

(Note, still not confirmed it fixes everything)

**Comment by awesomebytes** [comment]
Yeah, that fixes launching `rqt` and a bunch of plugins.

Proof:
![screenshot from 2018-12-14 18-13-16](https://user-images.githubusercontent.com/1721716/49988744-065d7700-ffcc-11e8-88d7-6fec494516a6.png)

@allenh1 Solution proposed: Add to `python-qt5-bindings` rosdistro key `dev-python/PyQt5[gui,widgets]` instead of the same without the USE flags. Do you agree?

**Comment by awesomebytes** [comment]
I've checked and in [rosdistro](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml) there is no gentoo key with USE flags as [USEflag]... maybe it's not possible? I don't know how to deal with this.

**Comment by awesomebytes** [comment]
@tfoote Do you have any suggestion on what to do here to pull the necessary dependencies on Gentoo?

**Comment by allenh1** [comment]
@awesomebytes see an example [here](https://github.com/ros/rosdistro/blob/5b3b76778a4a1b698048ab5834bd4b800804d208/rosdep/base.yaml#L385) of the USE flags in the bracket syntax.

That change would resolve this. Please also add `boost[python]` (I thought this was in there, apparently it isn't).

**Comment by awesomebytes** [comment]
PR created for python-qt5-bindings: https://github.com/ros/rosdistro/pull/19737

**Comment by awesomebytes** [comment]
The PR has been merged, closing
