### ISSUE TITLE
run superflore on ros-kinetic/naoqi_libqicore please?

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#756]
Hello @allenh1 I still don't have a working machine where to run superflore stuff... unfortunately.

I quickly explored using Docker-in-Docker to stop this annoyance but I couldn't find a quick tutorial on how to get it running.

I need `naoqi_libqicore` refreshed cause it can't be emerged right now with the error:
```
!!! Fetched file: naoqi_libqicore-release-2.3.1.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      135409
!!! Expected: 135396
```
But it would be good to just do all the pack I think:
```
naoqi_apps
naoqi_bridge
naoqi_bridge_msgs
naoqi_dcm_driver
naoqi_driver
naoqi_driver_py
naoqi_libqi
naoqi_libqicore
naoqi_pose
naoqi_sensors_py
naoqi_tools
```

Thank you!

**Comment by awesomebytes** [comment]
Just got the same on: `ros-kinetic/sbpl`

**Comment by allenh1** [comment]
@awesomebytes is this still needed? I'm more than happy to do so

**Comment by awesomebytes** [comment]
Just in case I ran it: https://github.com/ros/ros-overlay/pull/949
