### ISSUE TITLE
compile ros-melodic/qwt_dependency-1.1.0 failed

### ISSUE THREAD

**Issue by CrawlerSpider** [ros/ros-overlay#773]
I get the error below when i try to compile the package ros-melodic/qwt_dependency-1.1.0: 
`!!! Fetched file: qwt_dependency-melodic-release-1.1.0.tar.gz VERIFY FAILED!
!!! Reason: Failed on BLAKE2B verification
!!! Got:      bd58e0a642170c7325cdc4495273668ea82871d854d0734d68c4a0297eda50b0cfe10a29f2dcab4c0732c37abc86992fdf76690fed26143864f5d34606cf0328
!!! Expected: bbc47df278026ba5a463f1a01a670668216b3e146d4017b67eb94c7186dffeebe72f8453caaf2a4c3df0be6fb6a18dea89d4eef29f203262cd2b905db441248c
Refetching... File renamed to '/var/cache/portage/distfiles/qwt_dependency-melodic-release-1.1.0.tar.gz._checksum_failure_.1aey9w58'`

Possible solution is:
`ebuild  qwt_dependency-1.1.0.ebuild digest`

**Comment by DevonMorris** [comment]
I saw this error today while installing melodic as well. Changing the Manifest file in `/usr/local/portage/ros-melodic/qwt_dependency` helped me install it. But honestly, I'm not sure if that was the correct thing to do.

**Comment by allenh1** [comment]
@DevonMorris looks like I forgot to fix this one!

You can do so pretty quickly by just running this:

```
superflore-gen-ebuilds --only qwt_dependency --ros-distro melodic
```

(Or just wait for me to get around to it since it isn't blocking you)

**Comment by allenh1** [comment]
@DevonMorris thanks for reminding me, @CrawlerSpider thanks for reporting!

```
$ superflore-check-ebuilds --pkgs qwt_dependency --ros-distro melodic
>>>> testing gentoo package integrity
>>>> Working in temporary directory /tmp/tmpwzmfoysv
>>>> Running container with command string 'bash -c 'emaint sync -r ros-overlay &>> /tmp/tmpwzmfoysv/log.txt && emerge ros-melodic/qwt_dependency &>> /tmp/tmpwzmfoysv/log.txt''...
>>>> Docker container exited.
>>>> Cleaning up temporary directory /tmp/tmpwzmfoysv
>>>>   'ros-melodic/qwt_dependency': building
```

Looks like it should definitely be working now.
