### ISSUE TITLE
cv_bridge fail to process

### ISSUE THREAD

**Issue by 0novanta** [ros/ros-overlay#776]
I'm running Fedora 29.

When it processes cv_bridge package it stops with the following error:
```
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_cpp
[ 50%] Built target cv_bridge
[ 66%] Linking CXX shared library /home/Giuseppe/ros_catkin_ws/devel_isolated/cv_bridge/lib/python2.7/site-packages/cv_bridge/boost/cv_bridge_boost.so
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libboost_python.a(from_python.o): relocation R_X86_64_PC32 against symbol `PyExc_TypeError' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/cv_bridge_boost.dir/build.make:133: /home/Giuseppe/ros_catkin_ws/devel_isolated/cv_bridge/lib/python2.7/site-packages/cv_bridge/boost/cv_bridge_boost.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:751: src/CMakeFiles/cv_bridge_boost.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
I have no idea what to do. Thanks in advance!

**Comment by allenh1** [comment]
@0novanta are you running Gentoo? It looks like redhat from the logs there...

**Comment by 0novanta** [comment]
@allenh1 sorry I thought I edited the issue, I'm running Fedora 29.
However I've managed to install ROS Kinetic following [this guide](http://wiki.ros.org/docker/Tutorials/Docker#Installing_Docker) but I don't know if it's the same thing or if I need more passages to make ROS Kinetic runnable.
However I'd still like to know how to solve the issue above because I'd prefer to install it from source than using Docker.

**Comment by 0novanta** [comment]
Solved.
Solution:
downloading library boost-python2-devel, in Fedora: `sudo dnf install boost-pyhton2-devel`.
Then going to CMakeCache.txt in cv_bridge directory (or the package-that-fails's directory) look for libboost_python.a (as in `/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libboost_python.a(from_python.o): relocation R_X86_64_PC32 against symbol `PyExc_TypeError' can not be used when making a shared object; recompile with -fPIC` as specified by the given error) and simply rename it in libboost_python.so.
The problem is that .a libraries are static and .so libraries are dynamic and in order to make a shared object you'll need a dynamic library.

**Comment by allenh1** [comment]
@0novanta glad to know you got through it!

In the future, this repository is for Gentoo Linux installations. I don't mind when people come in with other-distro problems (for source building), but like to mark it clearly as such so that future visitors are clear about it.

Cheers!
