### ISSUE TITLE
move some RDEPEND to DEPEND

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#83]
easy task: move to `DEPEND` these dependencies

```
 RDEPEND.suspect               12
   ros-indigo/cob_obstacle_distance/cob_obstacle_distance-0.6.14.ebuild: 'virtual/pkgconfig'
   ros-indigo/gperftools_21/gperftools_21-2.1.0-r1.ebuild: 'dev-util/gperf'
   ros-indigo/orocos_kdl/orocos_kdl-1.3.1.ebuild: 'virtual/pkgconfig'
   ros-indigo/razer_hydra/razer_hydra-0.2.1.ebuild: 'virtual/pkgconfig'
   ros-indigo/rospack/rospack-2.2.8.ebuild: 'virtual/pkgconfig'
   ros-kinetic/orocos_kdl/orocos_kdl-1.3.1.ebuild: 'virtual/pkgconfig'
   ros-kinetic/rosdoc_lite/rosdoc_lite-0.2.7.ebuild: 'app-doc/doxygen'
   ros-kinetic/rospack/rospack-2.3.3.ebuild: 'virtual/pkgconfig'
   ros-kinetic/rtt/rtt-2.9.0-r2.ebuild: 'virtual/pkgconfig'
   ros-lunar/orocos_kdl/orocos_kdl-1.3.1.ebuild: 'virtual/pkgconfig'
   ros-lunar/rosdoc_lite/rosdoc_lite-0.2.7.ebuild: 'app-doc/doxygen'
   ros-lunar/rospack/rospack-2.4.1.ebuild: 'virtual/pkgconfig'
```

**Comment by allenh1** [comment]
@Alessandro-Barbieri Will do! In the future, please file these as issues on allenh1/ebuild-generator.

It's much easier for me to keep track of that way.

**Comment by archenroot** [comment]
@allenh1 I think @Alessandro-Barbieri already mentioned it somewhere and it is just another idea to consider -> taking your ebuild generator and integrate it into https://github.com/jauhien/g-sorcery. What do you think?

**Comment by allenh1** [comment]
@archenroot I have look through it, and it doesn't seem to be quite what I would need. Mine already supports the features it has currently (less the eclass, but that shouldn't need to be a feature of an ebuild generator).

The other issue is the fact that g-sorcery seems to lack things like patching, multiple keywords, and even things like licenses, build depends, and more that mine already supports.

But most importantly, that project looks to be dead. There are open pull requests that are several months old to which the maintainer has not responded.

If I had been looking at this in the beginning of this effort, that would be one thing, but, as it sits now, I just don't see a reason to use it / contribute to it.

**Comment by allenh1** [comment]
@Alessandro-Barbieri do you know if this is still a problem?

**Comment by Alessandro-Barbieri** [comment]
I don't know, it was an extract from a layman report.

I checked the first ebuild in the list manually and it's not fixed.

**Comment by allenh1** [comment]
Hm... Ok. Would you mind filing an issue on superflore that has a list of those packages which should be only listed as build depends?

**Comment by allenh1** [comment]
Ok, those fix the packages enumerated previously. If you find any others, let me know.

Closing for now.
