### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#84]
`/home/travis/build/ros/ros-overlay/travis-overlay/ros-indigo/network_control_tests/network_control_tests-1.0.11.ebuild: line 6: Test: command not found`

**Comment by Alessandro-Barbieri** [comment]
`/home/travis/build/ros/ros-overlay/travis-overlay/ros-indigo/genty/genty-1.3.0.ebuild: line 8: tests. It promotes generative: command not found`

**Comment by allenh1** [comment]
This should be resolved as of ros-infrastructure/superflore#36
