### ISSUE TITLE
rospack-2.5.4-r1 wants dev-python/rosdep and dev-util/rosdep

### ISSUE THREAD

**Issue by flabrosse** [ros/ros-overlay#868]
rospack-2.5.4-r1 wants both dev-python/resdep and dev-util/rosdep.  And the latter has collisions with the former, obviously.

**Comment by flabrosse** [comment]
Removing dev-util/rosdep from the dependencies in the ebuild seems to work fine.

**Comment by allenh1** [comment]
> Removing dev-util/rosdep from the dependencies in the ebuild seems to work fine.

@flabrosse would you mind submitting a PR with that change?

**Comment by flabrosse** [comment]
Have never done that so looking into it.  It seems that I either have to be able to create a new branch (which I don't think I have the permission to do) or to create a fork (which seems a bit overkill).  Suggestions?

**Comment by flabrosse** [comment]
I think it's created (fork seemed to be a lot less involved than expected).

**Comment by flabrosse** [comment]
Now fixed.
