### ISSUE TITLE
ImportError: No module named 'rosmake' - ros-lunar/rosmake-1.14.0::ros-overlay

### ISSUE THREAD

**Issue by archenroot** [ros/ros-overlay#87]
While std_msgs are having those troubles I tried to pull in some basic stuff for make, run, etc. and facing now following error with rosmake.

```
ares portage # equery f rosmake
 * Searching for rosmake ...
 * Contents of ros-lunar/rosmake-1.14.0:
/opt
/opt/ros
/opt/ros/lunar
/opt/ros/lunar/bin
/opt/ros/lunar/bin/rosmake
/opt/ros/lunar/lib
/opt/ros/lunar/lib/pkgconfig
/opt/ros/lunar/lib/pkgconfig/rosmake.pc
/opt/ros/lunar/lib64
/opt/ros/lunar/lib64/python3.5
/opt/ros/lunar/lib64/python3.5/site-packages
/opt/ros/lunar/lib64/python3.5/site-packages/rosmake
/opt/ros/lunar/lib64/python3.5/site-packages/rosmake-1.14.0-py3.5.egg-info
/opt/ros/lunar/lib64/python3.5/site-packages/rosmake/__init__.py
/opt/ros/lunar/lib64/python3.5/site-packages/rosmake/engine.py
/opt/ros/lunar/lib64/python3.5/site-packages/rosmake/gcc_output_parse.py
/opt/ros/lunar/lib64/python3.5/site-packages/rosmake/package_stats.py
/opt/ros/lunar/lib64/python3.5/site-packages/rosmake/parallel_build.py
/opt/ros/lunar/share
/opt/ros/lunar/share/rosmake
/opt/ros/lunar/share/rosmake/cmake
/opt/ros/lunar/share/rosmake/cmake/rosmakeConfig-version.cmake
/opt/ros/lunar/share/rosmake/cmake/rosmakeConfig.cmake
/opt/ros/lunar/share/rosmake/package.xml
```

So I checked python if rosmake is available and it isn't visible in python subsystem:
```
ares portage # pip list |grep ros
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
rosdep (0.11.5)
rosdistro (0.6.2)
rospkg (1.1.1)

```

**Comment by archenroot** [comment]
Actually here is error by trying to use it directly:
```
zangetsu@ares ~/proj/3d-frameworks/direct-sparse-odometry_ros $ python /opt/ros/lunar/bin/rosmake
Traceback (most recent call last):
  File "/opt/ros/lunar/bin/rosmake", line 40, in <module>
    import rosmake
ImportError: No module named 'rosmake'

```

**Comment by archenroot** [comment]
I think this is my fault as I didn't reconfigure my environment, I changed the paths of ROS env variables in ~/.bashrc to following:
```
export CMAKE_PREFIX_PATH=/usr
export PYTHONPATH=/usr/lib64/python3.5/site-packages/
export ROS_DISTRO=lunar
export ROS_ETC_DIR=/etc/ros
export ROS_MASTER_URI=http://ares:11311
export ROS_PACKAGE_PATH=/usr/share/ros_packages
export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:/home/zangetsu/proj/neural-networks/ORB_SLAM2/Examples/ROS
export ROS_ROOT=/opt/ros/lunar

```
Still doesn't work, but I think this is the root cause

**Comment by allenh1** [comment]
Ya, most of those are not right (and also don't need to be set).

**Comment by archenroot** [comment]
And how looks your ROS env? These are remaining blocks from Gentoo ROS tree work...

**Comment by allenh1** [comment]
I actually don't set any of those and just source `/opt/ros/setup.bash`

**Comment by archenroot** [comment]
The file will be doing most of it, but due to issue with std_msgs package I didn't finish the lunar install... so don't have this file :-).

Ok, I will install the kinetic as well and see how it works on my system, can i do kinect with 3.5 python as well?

**Comment by allenh1** [comment]
I meant `/opt/ros/lunar/setup.bash`

**Comment by allenh1** [comment]
> The file will be doing mostly the same, but due to issue with std_msgs package I didn't finish the lunar install... so don't have this file :-).

The setup file comes from catkin. You should have it. It will set everything up correctly with respect to environment, so you should still be able to do *some* things, though you didn't finish your lunar install.

**Comment by archenroot** [comment]
Right, ok, the file is under sh /opt/ros/lunar/setup.bash and is part of catkin package. Thx.

**Comment by archenroot** [comment]
I have now lunar rosmake working
