### ISSUE TITLE
lunar roscore: ImportError: No module named 'defusedxml'

### ISSUE THREAD

**Issue by archenroot** [ros/ros-overlay#89]
While testing roscore from lunar distro I encountered:
```
Traceback (most recent call last):
  File "/opt/ros/lunar/bin/roscore", line 36, in <module>
    from rosmaster.master_api import NUM_WORKERS
  File "/opt/ros/lunar/lib64/python3.5/site-packages/rosmaster/__init__.py", line 35, in <module>
    from .main import rosmaster_main
  File "/opt/ros/lunar/lib64/python3.5/site-packages/rosmaster/main.py", line 43, in <module>
    import rosmaster.master
  File "/opt/ros/lunar/lib64/python3.5/site-packages/rosmaster/master.py", line 47, in <module>
    import rosmaster.master_api
  File "/opt/ros/lunar/lib64/python3.5/site-packages/rosmaster/master_api.py", line 72, in <module>
    from rosmaster.util import xmlrpcapi
  File "/opt/ros/lunar/lib64/python3.5/site-packages/rosmaster/util.py", line 48, in <module>
    from defusedxml.xmlrpc import monkey_patch
ImportError: No module named 'defusedxml'

```

**Comment by allenh1** [comment]
I'm confused... Is this still an issue?

**Comment by archenroot** [comment]
I have quite experimental system here :-), so finally got it working but had to reemerge manually...

**Comment by dkati** [comment]
how did u solve that :) thanks

**Comment by allenh1** [comment]
He probably just didn't emerge it originally with python 3.5. Btw, you can now use Python 2.7 (which is likely best, since there are some ROS packages which still don't support Python 3).

**Comment by dkati** [comment]
i do use 2.7 but i still have the same problem :/ the catkin_make is done but roslaunch doesnt run for certain packages

**Comment by allenh1** [comment]
Hm... Do you mind filing a separate issue with more information?

Please include things like ros distro, install method (source based or portage based), the date you emerged things, etc.

**Comment by dkati** [comment]
i am on ros kinetic
Running 
roslaunch husky_gazebo husky_farm.launch laser_enabled:=false kinect_enabled:=true 
gives me the error.

here is the source of the package
https://github.com/ros-autom/husky

I touched the /opt dir and installed/removed some packages though...i didnt touch the source of the package...i guess i removed something that i shouldnt :P

**Comment by allenh1** [comment]
I don't think that package has been released in `ros-kinetic` yet. I'll try and build it from source when I get a few.

**Comment by allenh1** [comment]
@dkati What's the exact error you get? I get one that says it doesn't know what multimaster_launch is.
