### ISSUE TITLE
Can't install dev-python/wstool-0.1.10

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#9]
The emerge stops at line "error: can't copy 'build/sphinx/man/wstool.1': doesn't exist or not a regular file"

emerge -pqv '=dev-python/wstool-0.1.10::ros-overlay'  
[ebuild   R   ] dev-python/wstool-0.1.10  PYTHON_TARGETS="python2_7 -python3_3" 

The other needed info are here:
https://gist.github.com/Alessandro-Barbieri/756f9a85655198448ec2

**Comment by allenh1** [comment]
Current version of wstool is 0.1.13.
