### ISSUE TITLE
ros-kinetic/roscpp-1.12.14 not emerging with boost 1.71.0 in Gentoo (Prefix)

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#912]
In order to avoid downgrading boost in Gentoo (Prefix) as it's pulling 1.71.0 now (and 1.68 is not available anymore as was workaround before) I found that roscpp fails with:

```bash
Could NOT find Boost (missing: signals) (found version "1.71.0")
```
I made a simple patch that just removes from the CMakeLists.txt the requirement of signals:

https://gist.github.com/awesomebytes/65580b4f485ecfb8e6cc043de84a34a3

I did this as I've read in the internet that signals (now signals2) is header only and is always included in boost, so if you pull any boost dependency, it should be there.

**Comment by awesomebytes** [comment]
ros-kinetic/message_filters has the exact same issue. Same patch:

https://gist.github.com/awesomebytes/35c60347a1a9c2631517e4eaaf401f8a

**Comment by awesomebytes** [comment]
Same with ros-kinetic/tf2, same patch:

https://gist.github.com/awesomebytes/a854d9d86fbed9df451bea7783a63642

**Comment by awesomebytes** [comment]
ros-kinetic/actionlib has a different problem, but also coming from boost 1.71.0:

Cause it doesn't find a known conversion for the milliseconds method. (Sorry I just lost the output to copy paste it).

The patch for it:
https://gist.github.com/awesomebytes/e4c45a6532ff5b752f2c29615a2fd1a6

It needs to be fixed in all those places or other packages that depend on actionlib fail to build later on (like tf2_ros).

**Comment by awesomebytes** [comment]
Same with ros-kinetic/tf (not finding signals)

Patch:
https://gist.github.com/awesomebytes/91771be9d47bd76f134fdb1180419797

**Comment by awesomebytes** [comment]
Same for ros-kinetic/rviz (not finding signals)

Patch:
https://gist.github.com/awesomebytes/ed60cca5525be2945a62422289213e79

**Comment by flabrosse** [comment]
Before I masked the latest boost, ros-melodic was having similar problems.

**Comment by awesomebytes** [comment]
Same for ros-kinetic/laser_assembler (part ros-kinetic/perception):

Patch:
https://gist.github.com/awesomebytes/cd248963539466114e4c79173cc368f5

**Comment by awesomebytes** [comment]
Same for ros-kinetic/laser_filters:

Patch:
https://gist.github.com/awesomebytes/4b914cfda5c29b7882d230492315af95

**Comment by awesomebytes** [comment]
Same for ros-kinetic/image_view:

Patch:
https://gist.github.com/awesomebytes/0d850047ffeb80b14f4581149d300052

**Comment by allenh1** [comment]
> Before I masked the latest boost, ros-melodic was having similar problems.

@awesomebytes due to the very large number of patches required (and my current ability to apply them), I'll recommend this approach for now.

If you have time to file the patches, please do!

**Comment by allenh1** [comment]
> I did this as I've read in the internet that signals (now signals2) is header only and is always included in boost, so if you pull any boost dependency, it should be there.

@awesomebytes  Do you know which boost version this was added in?

I think we need to either switch to that version and greater, or apply these patches only when the boost version is that version or later.

**Comment by awesomebytes** [comment]
Haven't checked yet. I'll do soon and submit PRs.

I know the patch should be version dependant. My priority was to get a
fully bootstrapped system first, my bad.

**Comment by awesomebytes** [comment]
Same thing for ros-kinetic/fake_localization, patch:

https://gist.github.com/awesomebytes/a793542e0c84c09954b8a7c32597cea3

**Comment by awesomebytes** [comment]
Same thing for ros-kinetic/gmapping, patch:

https://gist.github.com/awesomebytes/e5d3d37c71b445caa06eb1b23e87142a

**Comment by flabrosse** [comment]
> > Before I masked the latest boost, ros-melodic was having similar problems.
> 
> @awesomebytes due to the very large number of patches required (and my current ability to apply them), I'll recommend this approach for now.
> 
The problem is that the previous version of boost has now been removed from the gentoo tree!  Just tried to update one of our robots and am now in a state with some packages updated but not all because they fail, and boost can't be reverted back to the previous version....

**Comment by awesomebytes** [comment]
I'm currently away of a computer for a bit more than a week.

My patches work and are enough to emerge from scratch up until
ros-kinetic/desktop (as part of this project:
https://github.com/awesomebytes/ros_overlay_on_gentoo_prefix with the CI
running here, in case anyone wants to check logs
https://dev.azure.com/12719821/12719821/_build?definitionId=5 I must say it
failed to completely emerge since yesterday as ros-kinetic/rqt_gui_cpp has
the -l-lpthread bug somehow again... Haven't resolved how it's happening,
it has nothing to do with the cmake version apparently... I also noticed
the issue 711 patch workaround is applied multiple times somehow? Anyways,
I'm diverging here).

So if you have the time to make a PR with them, that would be great!

**Comment by awesomebytes** [comment]
I made a PR to address all this, finally: https://github.com/ros/ros-overlay/pull/955

All patches have been tested and building nightly for a while.

**Comment by flabrosse** [comment]
This is great.  Unfortunately this does not solve the ros melodic similar issues.  I guess it's unlikely the patches will just work on melodic.

**Comment by awesomebytes** [comment]
In all fairness, I haven't tried. The ones that patch CMakeLists have a
high chance of working as they are.

**Comment by awesomebytes** [comment]
@flabrosse Apparently (I'm still running builds to test it) all upstream packages have been patched in melodic for the Boost issue.

**Comment by awesomebytes** [comment]
ros-melodic/tf is affected by this, pending a new release upstream: https://github.com/ros/geometry/issues/203

Meanwhile https://gist.github.com/awesomebytes/cee46d45d1314d8df4512ed577c55227 works.

**Comment by awesomebytes** [comment]
Everything fixed :) closing.
