### ISSUE TITLE
rospack-2.5.5-r1 depends on two different, colliding rosdep packages

### ISSUE THREAD

**Issue by flabrosse** [ros/ros-overlay#966]
I thought I had commented on that but can't find it.  the latest rospack (and previous versions) wants both dev-python/rosdep and dev-util/rosdep, which collide.

Removing the one from dev-util worked.

**Comment by awesomebytes** [comment]
Yeah, I made a PR: https://github.com/ros/ros-overlay/pull/965

**Comment by allenh1** [comment]
Hm... That's not so great... Wonder how that happened...

**Comment by allenh1** [comment]
With that PR merged, we should be good.
