### ISSUE TITLE
ros-melodic: tf depends on catkin which depends on catkin_pkg but no python version in common

### ISSUE THREAD

**Issue by fcolecumberri** [ros/ros-overlay#977]
In ros-melodic (maybe the same in other versions), tf is a only python2 ebuild, and depends on catkin and catkin depends on catkin_pkg, this is perfectly fine except that when I try to emerge I got the error:

~~~
ImportError: "from catkin_pkg.package import parse_package" failed: No module named catkin_pkg.package
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python2.7
  "/opt/ros/melodic/share/catkin/cmake/parse_package_xml.py"
  "/opt/ros/melodic/share/catkin/cmake/../package.xml"
  "/var/tmp/portage/ros-melodic/tf-1.12.1-r1/work/tf-1.12.1_build-python2_7/catkin/catkin_generated/version/package.cmake")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkin_package_xml.cmake:74 (safe_execute_process)
  /opt/ros/melodic/share/catkin/cmake/all.cmake:172 (_catkin_package_xml)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:16 (find_package)
~~~

I asume this error is because catkin_pkg now is a python3 only package, so no python2 catkin_pkg is there.

**Comment by awesomebytes** [comment]
I made this PR: https://github.com/ros/ros-overlay/pull/975 which would fix the issue as it still has support for python2.7

**Comment by flabrosse** [comment]
Related but maybe different issue here.  Trying to install the new tf2, which does support both python2 and 3, but fails to emerge when trying the support for python2_7 because no catkin_pkg for it.  I suspect the PR would solve that.

**Comment by awesomebytes** [comment]
@flabrosse I agree to believe merging that PR should fix both issues.

**Comment by awesomebytes** [comment]
This is fixed, right?

**Comment by fcolecumberri** [comment]
yea, sorry, closing the issue

**Comment by flabrosse** [comment]
Fixed for tf2 but not hector_mapping.

**Comment by awesomebytes** [comment]
@flabrosse How can that be?

https://github.com/ros/ros-overlay/blob/master/ros-melodic/hector_mapping/hector_mapping-0.4.0-r1.ebuild

Lists python2.7 as compatible. And [catkin_pkg](https://github.com/ros/ros-overlay/blob/master/dev-python/catkin_pkg/catkin_pkg-0.4.16.ebuild) has support for it. If this is a Python3.X issue, then I don't know. I haven't adventured into that...

**Comment by flabrosse** [comment]
Sorry, wrong discussion.  The remaining problem is with hector_mapping not finding boost signals.

Apologies, was too quick to respond :-(
