### ISSUE TITLE
ros-kinetic rosbridge_server dissapeared

### ISSUE THREAD

**Issue by awesomebytes** [ros/ros-overlay#982]
In this commit: https://github.com/ros/ros-overlay/commit/165e1756531eedecc7013ed8cc84c7ce2df3f0d4#diff-7e6c260fba0ebbef6eb045fbeab70d62

The `ros-kinetic/rosbridge_library` package has been removed from ros-overlay.

And in this commit: https://github.com/ros/ros-overlay/commit/165e1756531eedecc7013ed8cc84c7ce2df3f0d4#diff-82ffafdf0817c0cc7f86c988bffe978f

The `ros-melodic/rosbridge_library` package has been removed from ros-overlay.

Maybe it's a matter of re-running superflore and checking if there is an error with some key... but I don't have a machine to run that right now! If someone could take a look, that would be great (my CI is broken cause of this).

**Comment by awesomebytes** [comment]
Re-using the ticket as it's in the same topic... In https://github.com/ros/ros-overlay/commit/165e1756531eedecc7013ed8cc84c7ce2df3f0d4#diff-21f5e1a547eeb87c4863e4cb2f413df1 rosbridge_server was deleted.

It needs to be re-generated.

**Comment by allenh1** [comment]
@awesomebytes Yeah, there's a missing dependency.

```
$ superflore-gen-ebuilds --only rosbridge_server --ros-distro kinetic
>>>> "kinetic" distro detected...
>>>> Working in temporary directory /tmp/tmplw8av242
>>>> Creating new branch gentoo-bot-FQEmxypTlL...
>>>> 
>>>> Regenerating package 'rosbridge_server'...
!!!! Failed to resolve required dependencies for package rosbridge_server!
!!!!  unresolved: "python3-autobahn"
!!!! No packages generated successfully, exiting.
>>>> Cleaning up temporary directory /tmp/tmplw8av242
```

**Comment by awesomebytes** [comment]
That's a weird dependency to have on kinetic, which doesn't support Python
3 (I think).

I'll check later if there is a PR to add it, otherwise I may do it.

**Comment by allenh1** [comment]
> I'll check later if there is a PR to add it, otherwise I may do it.

I just did it, and got some more while I was at it. Should be fixed soon!
